// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Specifies the config of attached disk options for single VM instance.
public struct AttachedDiskConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Disk type.
  public var diskType: AttachedDiskConfig.DiskType = AttachedDiskConfig.DiskType()

  /// Optional. Disk size in GB.
  public var diskSizeGb: Swift.Int32 = Swift.Int32()

  /// Optional. Indicates how many IOPS to provision for the attached disk. This
  /// sets the number of I/O operations per second that the disk can handle. See
  /// https://cloud.google.com/compute/docs/disks/hyperdisks#hyperdisk-features
  public var provisionedIops: Swift.Int64? = nil

  /// Optional. Indicates how much throughput to provision for the attached
  /// disk. This sets the number of throughput mb per second that the disk can
  /// handle. See
  /// https://cloud.google.com/compute/docs/disks/hyperdisks#hyperdisk-features
  public var provisionedThroughput: Swift.Int64? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AttachedDiskConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AttachedDiskConfig().with { $0.diskType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let diskType = CodingKeys(stringValue: "diskType")
    static let diskSizeGb = CodingKeys(stringValue: "diskSizeGb")
    static let provisionedIops = CodingKeys(stringValue: "provisionedIops")
    static let provisionedThroughput = CodingKeys(stringValue: "provisionedThroughput")

    static let _knownKeys: Set<Swift.String> = [
      "diskType",
      "diskSizeGb",
      "provisionedIops",
      "provisionedThroughput",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      AttachedDiskConfig.DiskType.self, forKey: .diskType)
    {
      self.diskType = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .diskSizeGb) {
      self.diskSizeGb = value
    }
    self.provisionedIops = try container.decodeIfPresent(Swift.Int64.self, forKey: .provisionedIops)
    self.provisionedThroughput = try container.decodeIfPresent(
      Swift.Int64.self, forKey: .provisionedThroughput)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.diskType, forKey: .diskType)
    try container.encode(self.diskSizeGb, forKey: .diskSizeGb)
    try container.encodeIfPresent(self.provisionedIops, forKey: .provisionedIops)
    try container.encodeIfPresent(self.provisionedThroughput, forKey: .provisionedThroughput)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum DiskType: Codable, Equatable, Hashable, Sendable {
    /// Required unspecified disk type.
    case unspecified
    /// Hyperdisk Balanced disk type.
    case hyperdiskBalanced
    /// Hyperdisk Extreme disk type.
    case hyperdiskExtreme
    /// Hyperdisk ML disk type.
    case hyperdiskMl
    /// Hyperdisk Throughput disk type.
    case hyperdiskThroughput
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .hyperdiskBalanced: return 1
      case .hyperdiskExtreme: return 2
      case .hyperdiskMl: return 3
      case .hyperdiskThroughput: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DISK_TYPE_UNSPECIFIED"
      case .hyperdiskBalanced: return "HYPERDISK_BALANCED"
      case .hyperdiskExtreme: return "HYPERDISK_EXTREME"
      case .hyperdiskMl: return "HYPERDISK_ML"
      case .hyperdiskThroughput: return "HYPERDISK_THROUGHPUT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DiskType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DISK_TYPE_UNSPECIFIED": self = .unspecified
      case "HYPERDISK_BALANCED": self = .hyperdiskBalanced
      case "HYPERDISK_EXTREME": self = .hyperdiskExtreme
      case "HYPERDISK_ML": self = .hyperdiskMl
      case "HYPERDISK_THROUGHPUT": self = .hyperdiskThroughput
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DiskType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .hyperdiskBalanced
      case 2: self = .hyperdiskExtreme
      case 3: self = .hyperdiskMl
      case 4: self = .hyperdiskThroughput
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("DISK_TYPE_UNSPECIFIED")
      case .hyperdiskBalanced: return try container.encode("HYPERDISK_BALANCED")
      case .hyperdiskExtreme: return try container.encode("HYPERDISK_EXTREME")
      case .hyperdiskMl: return try container.encode("HYPERDISK_ML")
      case .hyperdiskThroughput: return try container.encode("HYPERDISK_THROUGHPUT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.AttachedDiskConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
