// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Basic autoscaling configurations for YARN.
public struct BasicYarnAutoscalingConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Timeout for YARN graceful decommissioning of Node Managers.
  /// Specifies the duration to wait for jobs to complete before forcefully
  /// removing workers (and potentially interrupting jobs). Only applicable to
  /// downscaling operations.
  ///
  /// Bounds: [0s, 1d].
  public var gracefulDecommissionTimeout: GoogleCloudWkt.Duration? = nil

  /// Required. Fraction of average YARN pending memory in the last cooldown
  /// period for which to add workers. A scale-up factor of 1.0 will result in
  /// scaling up so that there is no pending memory remaining after the update
  /// (more aggressive scaling). A scale-up factor closer to 0 will result in a
  /// smaller magnitude of scaling up (less aggressive scaling). See [How
  /// autoscaling
  /// works](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/autoscaling#how_autoscaling_works)
  /// for more information.
  ///
  /// Bounds: [0.0, 1.0].
  public var scaleUpFactor: Swift.Double = Swift.Double()

  /// Required. Fraction of average YARN pending memory in the last cooldown
  /// period for which to remove workers. A scale-down factor of 1 will result in
  /// scaling down so that there is no available memory remaining after the
  /// update (more aggressive scaling). A scale-down factor of 0 disables
  /// removing workers, which can be beneficial for autoscaling a single job.
  /// See [How autoscaling
  /// works](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/autoscaling#how_autoscaling_works)
  /// for more information.
  ///
  /// Bounds: [0.0, 1.0].
  public var scaleDownFactor: Swift.Double = Swift.Double()

  /// Optional. Minimum scale-up threshold as a fraction of total cluster size
  /// before scaling occurs. For example, in a 20-worker cluster, a threshold of
  /// 0.1 means the autoscaler must recommend at least a 2-worker scale-up for
  /// the cluster to scale. A threshold of 0 means the autoscaler will scale up
  /// on any recommended change.
  ///
  /// Bounds: [0.0, 1.0]. Default: 0.0.
  public var scaleUpMinWorkerFraction: Swift.Double = Swift.Double()

  /// Optional. Minimum scale-down threshold as a fraction of total cluster size
  /// before scaling occurs. For example, in a 20-worker cluster, a threshold of
  /// 0.1 means the autoscaler must recommend at least a 2 worker scale-down for
  /// the cluster to scale. A threshold of 0 means the autoscaler will scale down
  /// on any recommended change.
  ///
  /// Bounds: [0.0, 1.0]. Default: 0.0.
  public var scaleDownMinWorkerFraction: Swift.Double = Swift.Double()

  /// Initialize a new instance of `BasicYarnAutoscalingConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BasicYarnAutoscalingConfig().with { $0.gracefulDecommissionTimeout = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.BasicYarnAutoscalingConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
