// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The status of a cluster and its instances.
public struct ClusterStatus: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The cluster's state.
  public var state: ClusterStatus.State = ClusterStatus.State()

  /// Optional. Output only. Details of cluster's state.
  public var detail: Swift.String = Swift.String()

  /// Output only. Time when this state was entered (see JSON representation of
  /// [Timestamp](https://developers.google.com/protocol-buffers/docs/proto3#json)).
  public var stateStartTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Additional state information that includes
  /// status reported by the agent.
  public var substate: ClusterStatus.Substate = ClusterStatus.Substate()

  /// Initialize a new instance of `ClusterStatus`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ClusterStatus().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The cluster state.
  public enum State: Codable, Equatable, Sendable {
    /// The cluster state is unknown.
    case unknown
    /// The cluster is being created and set up. It is not ready for use.
    case creating
    /// The cluster is currently running and healthy. It is ready for use.
    ///
    /// **Note:** The cluster state changes from "creating" to "running" status
    /// after the master node(s), first two primary worker nodes (and the last
    /// primary worker node if primary workers > 2) are running.
    case running
    /// The cluster encountered an error. It is not ready for use.
    case error
    /// The cluster is being deleted. It cannot be used.
    case deleting
    /// The cluster is being updated. It continues to accept and process jobs.
    case updating
    /// The cluster is being stopped. It cannot be used.
    case stopping
    /// The cluster is currently stopped. It is not ready for use.
    case stopped
    /// The cluster is being started. It is not ready for use.
    case starting
    /// The cluster has encountered an error while being updated. Jobs can
    /// be submitted to the cluster, but the cluster cannot be updated.
    case errorDueToUpdate
    /// The cluster is being repaired. It is not ready for use.
    case repairing
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unknown
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unknown: return 0
      case .creating: return 1
      case .running: return 2
      case .error: return 3
      case .deleting: return 4
      case .updating: return 5
      case .stopping: return 6
      case .stopped: return 7
      case .starting: return 8
      case .errorDueToUpdate: return 9
      case .repairing: return 10
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unknown: return "UNKNOWN"
      case .creating: return "CREATING"
      case .running: return "RUNNING"
      case .error: return "ERROR"
      case .deleting: return "DELETING"
      case .updating: return "UPDATING"
      case .stopping: return "STOPPING"
      case .stopped: return "STOPPED"
      case .starting: return "STARTING"
      case .errorDueToUpdate: return "ERROR_DUE_TO_UPDATE"
      case .repairing: return "REPAIRING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNKNOWN": self = .unknown
      case "CREATING": self = .creating
      case "RUNNING": self = .running
      case "ERROR": self = .error
      case "ERROR_DUE_TO_UPDATE": self = .errorDueToUpdate
      case "DELETING": self = .deleting
      case "UPDATING": self = .updating
      case "STOPPING": self = .stopping
      case "STOPPED": self = .stopped
      case "STARTING": self = .starting
      case "REPAIRING": self = .repairing
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unknown
      case 1: self = .creating
      case 2: self = .running
      case 3: self = .error
      case 4: self = .deleting
      case 5: self = .updating
      case 6: self = .stopping
      case 7: self = .stopped
      case 8: self = .starting
      case 9: self = .errorDueToUpdate
      case 10: self = .repairing
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unknown: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .running: return try container.encode(2)
      case .error: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .updating: return try container.encode(5)
      case .stopping: return try container.encode(6)
      case .stopped: return try container.encode(7)
      case .starting: return try container.encode(8)
      case .errorDueToUpdate: return try container.encode(9)
      case .repairing: return try container.encode(10)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The cluster substate.
  public enum Substate: Codable, Equatable, Sendable {
    /// The cluster substate is unknown.
    case unspecified
    /// The cluster is known to be in an unhealthy state
    /// (for example, critical daemons are not running or HDFS capacity is
    /// exhausted).
    ///
    /// Applies to RUNNING state.
    case unhealthy
    /// The agent-reported status is out of date (may occur if
    /// Dataproc loses communication with Agent).
    ///
    /// Applies to RUNNING state.
    case staleStatus
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .unhealthy: return 1
      case .staleStatus: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "UNSPECIFIED"
      case .unhealthy: return "UNHEALTHY"
      case .staleStatus: return "STALE_STATUS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Substate/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNSPECIFIED": self = .unspecified
      case "UNHEALTHY": self = .unhealthy
      case "STALE_STATUS": self = .staleStatus
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Substate/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .unhealthy
      case 2: self = .staleStatus
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .unhealthy: return try container.encode(1)
      case .staleStatus: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.ClusterStatus"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
