// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Describes the identifying information, config, and status of
/// a Dataproc cluster
public struct Cluster: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The Google Cloud Platform project ID that the cluster belongs to.
  public var projectId: Swift.String = Swift.String()

  /// Required. The cluster name, which must be unique within a project.
  /// The name must start with a lowercase letter, and can contain
  /// up to 51 lowercase letters, numbers, and hyphens. It cannot end
  /// with a hyphen. The name of a deleted cluster can be reused.
  public var clusterName: Swift.String = Swift.String()

  /// Optional. The cluster config for a cluster of Compute Engine Instances.
  /// Note that Dataproc may set default values, and values may change
  /// when clusters are updated.
  ///
  /// Exactly one of ClusterConfig or VirtualClusterConfig must be specified.
  public var config: ClusterConfig? = nil

  /// Optional. The virtual cluster config is used when creating a Dataproc
  /// cluster that does not directly control the underlying compute resources,
  /// for example, when creating a [Dataproc-on-GKE
  /// cluster](https://cloud.google.com/dataproc/docs/guides/dpgke/dataproc-gke-overview).
  /// Dataproc may set default values, and values may change when
  /// clusters are updated. Exactly one of
  /// [config][google.cloud.dataproc.v1.Cluster.config] or
  /// [virtual_cluster_config][google.cloud.dataproc.v1.Cluster.virtual_cluster_config]
  /// must be specified.
  ///
  /// [google.cloud.dataproc.v1.Cluster.config]: <doc:Cluster/config>
  /// [google.cloud.dataproc.v1.Cluster.virtual_cluster_config]: <doc:Cluster/virtualClusterConfig>
  public var virtualClusterConfig: VirtualClusterConfig? = nil

  /// Optional. The labels to associate with this cluster.
  /// Label **keys** must contain 1 to 63 characters, and must conform to
  /// [RFC 1035](https://www.ietf.org/rfc/rfc1035.txt).
  /// Label **values** may be empty, but, if present, must contain 1 to 63
  /// characters, and must conform to [RFC
  /// 1035](https://www.ietf.org/rfc/rfc1035.txt). No more than 32 labels can be
  /// associated with a cluster.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Cluster status.
  public var status: ClusterStatus? = nil

  /// Output only. The previous cluster status.
  public var statusHistory: [ClusterStatus] = []

  /// Output only. A cluster UUID (Unique Universal Identifier). Dataproc
  /// generates this value when it creates the cluster.
  public var clusterUuid: Swift.String = Swift.String()

  /// Output only. Contains cluster daemon metrics such as HDFS and YARN stats.
  ///
  /// **Beta Feature**: This report is available for testing purposes only. It
  /// may be changed before final release.
  public var metrics: ClusterMetrics? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Cluster`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Cluster().with { $0.projectId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let projectId = CodingKeys(stringValue: "projectId")
    static let clusterName = CodingKeys(stringValue: "clusterName")
    static let config = CodingKeys(stringValue: "config")
    static let virtualClusterConfig = CodingKeys(stringValue: "virtualClusterConfig")
    static let labels = CodingKeys(stringValue: "labels")
    static let status = CodingKeys(stringValue: "status")
    static let statusHistory = CodingKeys(stringValue: "statusHistory")
    static let clusterUuid = CodingKeys(stringValue: "clusterUuid")
    static let metrics = CodingKeys(stringValue: "metrics")

    static let _knownKeys: Set<Swift.String> = [
      "projectId",
      "clusterName",
      "config",
      "virtualClusterConfig",
      "labels",
      "status",
      "statusHistory",
      "clusterUuid",
      "metrics",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clusterName) {
      self.clusterName = value
    }
    self.config = try container.decodeIfPresent(ClusterConfig.self, forKey: .config)
    self.virtualClusterConfig = try container.decodeIfPresent(
      VirtualClusterConfig.self, forKey: .virtualClusterConfig)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.status = try container.decodeIfPresent(ClusterStatus.self, forKey: .status)
    if let value = try container.decodeIfPresent([ClusterStatus].self, forKey: .statusHistory) {
      self.statusHistory = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clusterUuid) {
      self.clusterUuid = value
    }
    self.metrics = try container.decodeIfPresent(ClusterMetrics.self, forKey: .metrics)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.clusterName, forKey: .clusterName)
    try container.encodeIfPresent(self.config, forKey: .config)
    try container.encodeIfPresent(self.virtualClusterConfig, forKey: .virtualClusterConfig)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.status, forKey: .status)
    try container.encode(self.statusHistory, forKey: .statusHistory)
    try container.encode(self.clusterUuid, forKey: .clusterUuid)
    try container.encodeIfPresent(self.metrics, forKey: .metrics)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.Cluster"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
