// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The cluster config.
public struct ClusterConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The type of the cluster.
  public var clusterType: ClusterConfig.ClusterType = ClusterConfig.ClusterType()

  /// Optional. The cluster tier.
  public var clusterTier: ClusterConfig.ClusterTier = ClusterConfig.ClusterTier()

  /// Optional. The cluster engine.
  public var engine: ClusterConfig.Engine = ClusterConfig.Engine()

  /// Optional. A Cloud Storage bucket used to stage job
  /// dependencies, config files, and job driver console output.
  /// If you do not specify a staging bucket, Cloud
  /// Dataproc will determine a Cloud Storage location (US,
  /// ASIA, or EU) for your cluster's staging bucket according to the
  /// Compute Engine zone where your cluster is deployed, and then create
  /// and manage this project-level, per-location bucket (see
  /// [Dataproc staging and temp
  /// buckets](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/staging-bucket)).
  /// **This field requires a Cloud Storage bucket name, not a `gs://...` URI to
  /// a Cloud Storage bucket.**
  public var configBucket: Swift.String = Swift.String()

  /// Optional. A Cloud Storage bucket used to store ephemeral cluster and jobs
  /// data, such as Spark and MapReduce history files. If you do not specify a
  /// temp bucket, Dataproc will determine a Cloud Storage location (US, ASIA, or
  /// EU) for your cluster's temp bucket according to the Compute Engine zone
  /// where your cluster is deployed, and then create and manage this
  /// project-level, per-location bucket. The default bucket has a TTL of 90
  /// days, but you can use any TTL (or none) if you specify a bucket (see
  /// [Dataproc staging and temp
  /// buckets](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/staging-bucket)).
  /// **This field requires a Cloud Storage bucket name, not a `gs://...` URI to
  /// a Cloud Storage bucket.**
  public var tempBucket: Swift.String = Swift.String()

  /// Optional. The shared Compute Engine config settings for
  /// all instances in a cluster.
  public var gceClusterConfig: GceClusterConfig? = nil

  /// Optional. The Compute Engine config settings for
  /// the cluster's master instance.
  public var masterConfig: InstanceGroupConfig? = nil

  /// Optional. The Compute Engine config settings for
  /// the cluster's worker instances.
  public var workerConfig: InstanceGroupConfig? = nil

  /// Optional. The Compute Engine config settings for
  /// a cluster's secondary worker instances
  public var secondaryWorkerConfig: InstanceGroupConfig? = nil

  /// Optional. The config settings for cluster software.
  public var softwareConfig: SoftwareConfig? = nil

  /// Optional. Commands to execute on each node after config is
  /// completed. By default, executables are run on master and all worker nodes.
  /// You can test a node's `role` metadata to run an executable on
  /// a master or worker node, as shown below using `curl` (you can also use
  /// `wget`):
  ///
  ///     ROLE=$(curl -H Metadata-Flavor:Google
  ///     http://metadata/computeMetadata/v1/instance/attributes/dataproc-role)
  ///     if [[ "${ROLE}" == 'Master' ]]; then
  ///       ... master specific actions ...
  ///     else
  ///       ... worker specific actions ...
  ///     fi
  public var initializationActions: [NodeInitializationAction] = []

  /// Optional. Encryption settings for the cluster.
  public var encryptionConfig: EncryptionConfig? = nil

  /// Optional. Autoscaling config for the policy associated with the cluster.
  /// Cluster does not autoscale if this field is unset.
  public var autoscalingConfig: AutoscalingConfig? = nil

  /// Optional. Security settings for the cluster.
  public var securityConfig: SecurityConfig? = nil

  /// Optional. Lifecycle setting for the cluster.
  public var lifecycleConfig: LifecycleConfig? = nil

  /// Optional. Port/endpoint configuration for this cluster
  public var endpointConfig: EndpointConfig? = nil

  /// Optional. Metastore configuration.
  public var metastoreConfig: MetastoreConfig? = nil

  /// Optional. The config for Dataproc metrics.
  public var dataprocMetricConfig: DataprocMetricConfig? = nil

  /// Optional. The node group settings.
  public var auxiliaryNodeGroups: [AuxiliaryNodeGroup] = []

  /// Initialize a new instance of `ClusterConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ClusterConfig().with { $0.clusterType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The type of the cluster.
  public enum ClusterType: Codable, Equatable, Sendable {
    /// Not set.
    case unspecified
    /// Standard dataproc cluster with a minimum of two primary workers.
    case standard
    /// https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/single-node-clusters
    case singleNode
    /// Clusters that can use only secondary workers and be scaled down to zero
    /// secondary worker nodes.
    case zeroScale
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .standard: return 1
      case .singleNode: return 2
      case .zeroScale: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CLUSTER_TYPE_UNSPECIFIED"
      case .standard: return "STANDARD"
      case .singleNode: return "SINGLE_NODE"
      case .zeroScale: return "ZERO_SCALE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ClusterType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CLUSTER_TYPE_UNSPECIFIED": self = .unspecified
      case "STANDARD": self = .standard
      case "SINGLE_NODE": self = .singleNode
      case "ZERO_SCALE": self = .zeroScale
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ClusterType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .standard
      case 2: self = .singleNode
      case 3: self = .zeroScale
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .standard: return try container.encode(1)
      case .singleNode: return try container.encode(2)
      case .zeroScale: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The cluster tier.
  public enum ClusterTier: Codable, Equatable, Sendable {
    /// Not set. Works the same as CLUSTER_TIER_STANDARD.
    case unspecified
    /// Standard Dataproc cluster.
    case standard
    /// Premium Dataproc cluster.
    case premium
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .standard: return 1
      case .premium: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CLUSTER_TIER_UNSPECIFIED"
      case .standard: return "CLUSTER_TIER_STANDARD"
      case .premium: return "CLUSTER_TIER_PREMIUM"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ClusterTier/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CLUSTER_TIER_UNSPECIFIED": self = .unspecified
      case "CLUSTER_TIER_STANDARD": self = .standard
      case "CLUSTER_TIER_PREMIUM": self = .premium
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ClusterTier/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .standard
      case 2: self = .premium
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .standard: return try container.encode(1)
      case .premium: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The cluster engine.
  public enum Engine: Codable, Equatable, Sendable {
    /// The engine is not specified. Works the same as ENGINE_DEFAULT.
    case unspecified
    /// The cluster is a default engine cluster.
    case `default`
    /// The cluster is a lightning engine cluster.
    case lightning
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`default`: return 1
      case .lightning: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ENGINE_UNSPECIFIED"
      case .`default`: return "DEFAULT"
      case .lightning: return "LIGHTNING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Engine/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ENGINE_UNSPECIFIED": self = .unspecified
      case "DEFAULT": self = .`default`
      case "LIGHTNING": self = .lightning
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Engine/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`default`
      case 2: self = .lightning
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .`default`: return try container.encode(1)
      case .lightning: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.ClusterConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
