// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Metadata describing the operation.
public struct ClusterOperationMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Name of the cluster for the operation.
  public var clusterName: Swift.String = Swift.String()

  /// Output only. Cluster UUID for the operation.
  public var clusterUuid: Swift.String = Swift.String()

  /// Output only. Current operation status.
  public var status: ClusterOperationStatus? = nil

  /// Output only. The previous operation status.
  public var statusHistory: [ClusterOperationStatus] = []

  /// Output only. The operation type.
  public var operationType: Swift.String = Swift.String()

  /// Output only. Short description of operation.
  public var description: Swift.String = Swift.String()

  /// Output only. Labels associated with the operation
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Errors encountered during operation execution.
  public var warnings: [Swift.String] = []

  /// Output only. Child operation ids
  public var childOperationIds: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ClusterOperationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ClusterOperationMetadata().with { $0.clusterName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let clusterName = CodingKeys(stringValue: "clusterName")
    static let clusterUuid = CodingKeys(stringValue: "clusterUuid")
    static let status = CodingKeys(stringValue: "status")
    static let statusHistory = CodingKeys(stringValue: "statusHistory")
    static let operationType = CodingKeys(stringValue: "operationType")
    static let description = CodingKeys(stringValue: "description")
    static let labels = CodingKeys(stringValue: "labels")
    static let warnings = CodingKeys(stringValue: "warnings")
    static let childOperationIds = CodingKeys(stringValue: "childOperationIds")

    static let _knownKeys: Set<Swift.String> = [
      "clusterName",
      "clusterUuid",
      "status",
      "statusHistory",
      "operationType",
      "description",
      "labels",
      "warnings",
      "childOperationIds",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clusterName) {
      self.clusterName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clusterUuid) {
      self.clusterUuid = value
    }
    self.status = try container.decodeIfPresent(ClusterOperationStatus.self, forKey: .status)
    if let value = try container.decodeIfPresent(
      [ClusterOperationStatus].self, forKey: .statusHistory)
    {
      self.statusHistory = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .operationType) {
      self.operationType = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .warnings) {
      self.warnings = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .childOperationIds) {
      self.childOperationIds = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.clusterName, forKey: .clusterName)
    try container.encode(self.clusterUuid, forKey: .clusterUuid)
    try container.encodeIfPresent(self.status, forKey: .status)
    try container.encode(self.statusHistory, forKey: .statusHistory)
    try container.encode(self.operationType, forKey: .operationType)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.warnings, forKey: .warnings)
    try container.encode(self.childOperationIds, forKey: .childOperationIds)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.ClusterOperationMetadata"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
