// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Cluster components that can be activated.
public enum Component: Codable, Equatable, Sendable {
  /// Unspecified component. Specifying this will cause Cluster creation to fail.
  case unspecified
  /// The Jupyter Notebook.
  case jupyter
  /// The Hive Web HCatalog (the REST service for accessing HCatalog).
  case hiveWebhcat
  /// The Zeppelin notebook.
  case zeppelin
  /// The Anaconda component is no longer supported or applicable to
  /// [supported Dataproc on Compute Engine image versions]
  /// (https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-version-clusters#supported-dataproc-image-versions).
  /// It cannot be activated on clusters created with supported Dataproc on
  /// Compute Engine image versions.
  case anaconda
  /// The Presto query engine.
  case presto
  /// The Zookeeper service.
  case zookeeper
  /// The Druid query engine. (alpha)
  case druid
  /// The Solr service.
  case solr
  /// HBase. (beta)
  case hbase
  /// The Ranger service.
  case ranger
  /// Docker
  case docker
  /// Flink
  case flink
  /// The Trino query engine.
  case trino
  /// Hudi.
  case hudi
  /// Iceberg.
  case iceberg
  /// Delta Lake.
  case delta
  /// The Pig component.
  case pig
  /// The Jupyter Kernel Gateway.
  case jupyterKernelGateway
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .jupyter: return 1
    case .hiveWebhcat: return 3
    case .zeppelin: return 4
    case .anaconda: return 5
    case .presto: return 6
    case .zookeeper: return 8
    case .druid: return 9
    case .solr: return 10
    case .hbase: return 11
    case .ranger: return 12
    case .docker: return 13
    case .flink: return 14
    case .trino: return 17
    case .hudi: return 18
    case .iceberg: return 19
    case .delta: return 20
    case .pig: return 21
    case .jupyterKernelGateway: return 22
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "COMPONENT_UNSPECIFIED"
    case .jupyter: return "JUPYTER"
    case .hiveWebhcat: return "HIVE_WEBHCAT"
    case .zeppelin: return "ZEPPELIN"
    case .anaconda: return "ANACONDA"
    case .presto: return "PRESTO"
    case .zookeeper: return "ZOOKEEPER"
    case .druid: return "DRUID"
    case .solr: return "SOLR"
    case .hbase: return "HBASE"
    case .ranger: return "RANGER"
    case .docker: return "DOCKER"
    case .flink: return "FLINK"
    case .trino: return "TRINO"
    case .hudi: return "HUDI"
    case .iceberg: return "ICEBERG"
    case .delta: return "DELTA"
    case .pig: return "PIG"
    case .jupyterKernelGateway: return "JUPYTER_KERNEL_GATEWAY"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Component/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "COMPONENT_UNSPECIFIED": self = .unspecified
    case "ANACONDA": self = .anaconda
    case "DELTA": self = .delta
    case "DOCKER": self = .docker
    case "DRUID": self = .druid
    case "FLINK": self = .flink
    case "HBASE": self = .hbase
    case "HIVE_WEBHCAT": self = .hiveWebhcat
    case "HUDI": self = .hudi
    case "ICEBERG": self = .iceberg
    case "JUPYTER": self = .jupyter
    case "PIG": self = .pig
    case "PRESTO": self = .presto
    case "TRINO": self = .trino
    case "RANGER": self = .ranger
    case "SOLR": self = .solr
    case "ZEPPELIN": self = .zeppelin
    case "ZOOKEEPER": self = .zookeeper
    case "JUPYTER_KERNEL_GATEWAY": self = .jupyterKernelGateway
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Component/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .jupyter
    case 3: self = .hiveWebhcat
    case 4: self = .zeppelin
    case 5: self = .anaconda
    case 6: self = .presto
    case 8: self = .zookeeper
    case 9: self = .druid
    case 10: self = .solr
    case 11: self = .hbase
    case 12: self = .ranger
    case 13: self = .docker
    case 14: self = .flink
    case 17: self = .trino
    case 18: self = .hudi
    case 19: self = .iceberg
    case 20: self = .delta
    case 21: self = .pig
    case 22: self = .jupyterKernelGateway
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .jupyter: return try container.encode(1)
    case .hiveWebhcat: return try container.encode(3)
    case .zeppelin: return try container.encode(4)
    case .anaconda: return try container.encode(5)
    case .presto: return try container.encode(6)
    case .zookeeper: return try container.encode(8)
    case .druid: return try container.encode(9)
    case .solr: return try container.encode(10)
    case .hbase: return try container.encode(11)
    case .ranger: return try container.encode(12)
    case .docker: return try container.encode(13)
    case .flink: return try container.encode(14)
    case .trino: return try container.encode(17)
    case .hudi: return try container.encode(18)
    case .iceberg: return try container.encode(19)
    case .delta: return try container.encode(20)
    case .pig: return try container.encode(21)
    case .jupyterKernelGateway: return try container.encode(22)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
