// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A request to create a cluster.
public struct CreateClusterRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The ID of the Google Cloud Platform project that the cluster
  /// belongs to.
  public var projectId: Swift.String = Swift.String()

  /// Required. The Dataproc region in which to handle the request.
  public var region: Swift.String = Swift.String()

  /// Required. The cluster to create.
  public var cluster: Cluster? = nil

  /// Optional. A unique ID used to identify the request. If the server receives
  /// two
  /// [CreateClusterRequest](https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#google.cloud.dataproc.v1.CreateClusterRequest)s
  /// with the same id, then the second request will be ignored and the
  /// first [google.longrunning.Operation][google.longrunning.Operation] created
  /// and stored in the backend is returned.
  ///
  /// It is recommended to always set this value to a
  /// [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier).
  ///
  /// The ID must contain only letters (a-z, A-Z), numbers (0-9),
  /// underscores (_), and hyphens (-). The maximum length is 40 characters.
  ///
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  public var requestId: Swift.String = Swift.String()

  /// Optional. Failure action when primary worker creation fails.
  public var actionOnFailedPrimaryWorkers: FailureAction = FailureAction()

  /// Initialize a new instance of `CreateClusterRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateClusterRequest().with { $0.projectId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.CreateClusterRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
