// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A request to create a cluster.
public struct CreateClusterRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The ID of the Google Cloud Platform project that the cluster
  /// belongs to.
  public var projectId: Swift.String = Swift.String()

  /// Required. The Dataproc region in which to handle the request.
  public var region: Swift.String = Swift.String()

  /// Required. The cluster to create.
  public var cluster: Cluster? = nil

  /// Optional. A unique ID used to identify the request. If the server receives
  /// two
  /// [CreateClusterRequest](https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#google.cloud.dataproc.v1.CreateClusterRequest)s
  /// with the same id, then the second request will be ignored and the
  /// first [google.longrunning.Operation][google.longrunning.Operation] created
  /// and stored in the backend is returned.
  ///
  /// It is recommended to always set this value to a
  /// [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier).
  ///
  /// The ID must contain only letters (a-z, A-Z), numbers (0-9),
  /// underscores (_), and hyphens (-). The maximum length is 40 characters.
  ///
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  public var requestId: Swift.String = Swift.String()

  /// Optional. Failure action when primary worker creation fails.
  public var actionOnFailedPrimaryWorkers: FailureAction = FailureAction()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateClusterRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateClusterRequest().with { $0.projectId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let projectId = CodingKeys(stringValue: "projectId")
    static let region = CodingKeys(stringValue: "region")
    static let cluster = CodingKeys(stringValue: "cluster")
    static let requestId = CodingKeys(stringValue: "requestId")
    static let actionOnFailedPrimaryWorkers = CodingKeys(
      stringValue: "actionOnFailedPrimaryWorkers")

    static let _knownKeys: Set<Swift.String> = [
      "projectId",
      "region",
      "cluster",
      "requestId",
      "actionOnFailedPrimaryWorkers",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .region) {
      self.region = value
    }
    self.cluster = try container.decodeIfPresent(Cluster.self, forKey: .cluster)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .requestId) {
      self.requestId = value
    }
    if let value = try container.decodeIfPresent(
      FailureAction.self, forKey: .actionOnFailedPrimaryWorkers)
    {
      self.actionOnFailedPrimaryWorkers = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.region, forKey: .region)
    try container.encodeIfPresent(self.cluster, forKey: .cluster)
    try container.encode(self.requestId, forKey: .requestId)
    try container.encode(self.actionOnFailedPrimaryWorkers, forKey: .actionOnFailedPrimaryWorkers)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.CreateClusterRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
