// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Dataproc metric config.
public struct DataprocMetricConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Metrics sources to enable.
  public var metrics: [DataprocMetricConfig.Metric] = []

  /// Initialize a new instance of `DataprocMetricConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataprocMetricConfig().with { $0.metrics = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A Dataproc custom metric.
  public struct Metric: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. A standard set of metrics is collected unless `metricOverrides`
    /// are specified for the metric source (see [Custom metrics]
    /// (https://cloud.google.com/dataproc/docs/guides/dataproc-metrics#custom_metrics)
    /// for more information).
    public var metricSource: DataprocMetricConfig.MetricSource = DataprocMetricConfig.MetricSource()

    /// Optional. Specify one or more [Custom metrics]
    /// (https://cloud.google.com/dataproc/docs/guides/dataproc-metrics#custom_metrics)
    /// to collect for the metric course (for the `SPARK` metric source (any
    /// [Spark metric]
    /// (https://spark.apache.org/docs/latest/monitoring.html#metrics) can be
    /// specified).
    ///
    /// Provide metrics in the following format:
    /// <code><var>METRIC_SOURCE</var>:<var>INSTANCE</var>:<var>GROUP</var>:<var>METRIC</var></code>
    /// Use camelcase as appropriate.
    ///
    /// Examples:
    ///
    /// ```
    /// yarn:ResourceManager:QueueMetrics:AppsCompleted
    /// spark:driver:DAGScheduler:job.allJobs
    /// sparkHistoryServer:JVM:Memory:NonHeapMemoryUsage.committed
    /// hiveserver2:JVM:Memory:NonHeapMemoryUsage.used
    /// ```
    ///
    /// Notes:
    ///
    /// * Only the specified overridden metrics are collected for the
    ///   metric source. For example, if one or more `spark:executive` metrics
    ///   are listed as metric overrides, other `SPARK` metrics are not
    ///   collected. The collection of the metrics for other enabled custom
    ///   metric sources is unaffected. For example, if both `SPARK` andd `YARN`
    ///   metric sources are enabled, and overrides are provided for Spark
    ///   metrics only, all YARN metrics are collected.
    public var metricOverrides: [Swift.String] = []

    /// Initialize a new instance of `Metric`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Metric().with { $0.metricSource = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataproc.v1.DataprocMetricConfig.Metric"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A source for the collection of Dataproc custom metrics (see [Custom
  /// metrics]
  /// (https://cloud.google.com//dataproc/docs/guides/dataproc-metrics#custom_metrics)).
  public enum MetricSource: Codable, Equatable, Sendable {
    /// Required unspecified metric source.
    case unspecified
    /// Monitoring agent metrics. If this source is enabled,
    /// Dataproc enables the monitoring agent in Compute Engine,
    /// and collects monitoring agent metrics, which are published
    /// with an `agent.googleapis.com` prefix.
    case monitoringAgentDefaults
    /// HDFS metric source.
    case hdfs
    /// Spark metric source.
    case spark
    /// YARN metric source.
    case yarn
    /// Spark History Server metric source.
    case sparkHistoryServer
    /// Hiveserver2 metric source.
    case hiveserver2
    /// hivemetastore metric source
    case hivemetastore
    /// flink metric source
    case flink
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .monitoringAgentDefaults: return 1
      case .hdfs: return 2
      case .spark: return 3
      case .yarn: return 4
      case .sparkHistoryServer: return 5
      case .hiveserver2: return 6
      case .hivemetastore: return 7
      case .flink: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "METRIC_SOURCE_UNSPECIFIED"
      case .monitoringAgentDefaults: return "MONITORING_AGENT_DEFAULTS"
      case .hdfs: return "HDFS"
      case .spark: return "SPARK"
      case .yarn: return "YARN"
      case .sparkHistoryServer: return "SPARK_HISTORY_SERVER"
      case .hiveserver2: return "HIVESERVER2"
      case .hivemetastore: return "HIVEMETASTORE"
      case .flink: return "FLINK"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:MetricSource/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "METRIC_SOURCE_UNSPECIFIED": self = .unspecified
      case "MONITORING_AGENT_DEFAULTS": self = .monitoringAgentDefaults
      case "HDFS": self = .hdfs
      case "SPARK": self = .spark
      case "YARN": self = .yarn
      case "SPARK_HISTORY_SERVER": self = .sparkHistoryServer
      case "HIVESERVER2": self = .hiveserver2
      case "HIVEMETASTORE": self = .hivemetastore
      case "FLINK": self = .flink
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:MetricSource/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .monitoringAgentDefaults
      case 2: self = .hdfs
      case 3: self = .spark
      case 4: self = .yarn
      case 5: self = .sparkHistoryServer
      case 6: self = .hiveserver2
      case 7: self = .hivemetastore
      case 8: self = .flink
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .monitoringAgentDefaults: return try container.encode(1)
      case .hdfs: return try container.encode(2)
      case .spark: return try container.encode(3)
      case .yarn: return try container.encode(4)
      case .sparkHistoryServer: return try container.encode(5)
      case .hiveserver2: return try container.encode(6)
      case .hivemetastore: return try container.encode(7)
      case .flink: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.DataprocMetricConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
