// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Encryption settings for the cluster.
public struct EncryptionConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The Cloud KMS key resource name to use for persistent disk
  /// encryption for all instances in the cluster. See [Use CMEK with cluster
  /// data]
  /// (https://cloud.google.com//dataproc/docs/concepts/configuring-clusters/customer-managed-encryption#use_cmek_with_cluster_data)
  /// for more information.
  public var gcePdKmsKeyName: Swift.String = Swift.String()

  /// Optional. The Cloud KMS key resource name to use for cluster persistent
  /// disk and job argument encryption. See [Use CMEK with cluster data]
  /// (https://cloud.google.com//dataproc/docs/concepts/configuring-clusters/customer-managed-encryption#use_cmek_with_cluster_data)
  /// for more information.
  ///
  /// When this key resource name is provided, the following job arguments of
  /// the following job types submitted to the cluster are encrypted using CMEK:
  ///
  /// * [FlinkJob
  /// args](https://cloud.google.com/dataproc/docs/reference/rest/v1/FlinkJob)
  /// * [HadoopJob
  /// args](https://cloud.google.com/dataproc/docs/reference/rest/v1/HadoopJob)
  /// * [SparkJob
  /// args](https://cloud.google.com/dataproc/docs/reference/rest/v1/SparkJob)
  /// * [SparkRJob
  /// args](https://cloud.google.com/dataproc/docs/reference/rest/v1/SparkRJob)
  /// * [PySparkJob
  /// args](https://cloud.google.com/dataproc/docs/reference/rest/v1/PySparkJob)
  /// * [SparkSqlJob](https://cloud.google.com/dataproc/docs/reference/rest/v1/SparkSqlJob)
  ///   scriptVariables and queryList.queries
  /// * [HiveJob](https://cloud.google.com/dataproc/docs/reference/rest/v1/HiveJob)
  ///   scriptVariables and queryList.queries
  /// * [PigJob](https://cloud.google.com/dataproc/docs/reference/rest/v1/PigJob)
  ///   scriptVariables and queryList.queries
  /// * [PrestoJob](https://cloud.google.com/dataproc/docs/reference/rest/v1/PrestoJob)
  ///   scriptVariables and queryList.queries
  public var kmsKey: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EncryptionConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EncryptionConfig().with { $0.gcePdKmsKeyName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcePdKmsKeyName = CodingKeys(stringValue: "gcePdKmsKeyName")
    static let kmsKey = CodingKeys(stringValue: "kmsKey")

    static let _knownKeys: Set<Swift.String> = [
      "gcePdKmsKeyName",
      "kmsKey",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gcePdKmsKeyName) {
      self.gcePdKmsKeyName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKey) {
      self.kmsKey = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.gcePdKmsKeyName, forKey: .gcePdKmsKeyName)
    try container.encode(self.kmsKey, forKey: .kmsKey)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.EncryptionConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
