// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// GKE node pools that Dataproc workloads run on.
public struct GkeNodePoolTarget: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The target GKE node pool.
  /// Format:
  /// 'projects/{project}/locations/{location}/clusters/{cluster}/nodePools/{node_pool}'
  public var nodePool: Swift.String = Swift.String()

  /// Required. The roles associated with the GKE node pool.
  public var roles: [GkeNodePoolTarget.Role] = []

  /// Input only. The configuration for the GKE node pool.
  ///
  /// If specified, Dataproc attempts to create a node pool with the
  /// specified shape. If one with the same name already exists, it is
  /// verified against all specified fields. If a field differs, the
  /// virtual cluster creation will fail.
  ///
  /// If omitted, any node pool with the specified name is used. If a
  /// node pool with the specified name does not exist, Dataproc create a
  /// node pool with default values.
  ///
  /// This is an input only field. It will not be returned by the API.
  public var nodePoolConfig: GkeNodePoolConfig? = nil

  /// Initialize a new instance of `GkeNodePoolTarget`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GkeNodePoolTarget().with { $0.nodePool = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// `Role` specifies the tasks that will run on the node pool. Roles can be
  /// specific to workloads. Exactly one
  /// [GkeNodePoolTarget][google.cloud.dataproc.v1.GkeNodePoolTarget] within the
  /// virtual cluster must have the `DEFAULT` role, which is used to run all
  /// workloads that are not associated with a node pool.
  ///
  /// [google.cloud.dataproc.v1.GkeNodePoolTarget]: <doc:GkeNodePoolTarget>
  public enum Role: Codable, Equatable, Sendable {
    /// Role is unspecified.
    case unspecified
    /// At least one node pool must have the `DEFAULT` role.
    /// Work assigned to a role that is not associated with a node pool
    /// is assigned to the node pool with the `DEFAULT` role. For example,
    /// work assigned to the `CONTROLLER` role will be assigned to the node pool
    /// with the `DEFAULT` role if no node pool has the `CONTROLLER` role.
    case `default`
    /// Run work associated with the Dataproc control plane (for example,
    /// controllers and webhooks). Very low resource requirements.
    case controller
    /// Run work associated with a Spark driver of a job.
    case sparkDriver
    /// Run work associated with a Spark executor of a job.
    case sparkExecutor
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`default`: return 1
      case .controller: return 2
      case .sparkDriver: return 3
      case .sparkExecutor: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ROLE_UNSPECIFIED"
      case .`default`: return "DEFAULT"
      case .controller: return "CONTROLLER"
      case .sparkDriver: return "SPARK_DRIVER"
      case .sparkExecutor: return "SPARK_EXECUTOR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Role/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ROLE_UNSPECIFIED": self = .unspecified
      case "DEFAULT": self = .`default`
      case "CONTROLLER": self = .controller
      case "SPARK_DRIVER": self = .sparkDriver
      case "SPARK_EXECUTOR": self = .sparkExecutor
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Role/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`default`
      case 2: self = .controller
      case 3: self = .sparkDriver
      case 4: self = .sparkExecutor
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .`default`: return try container.encode(1)
      case .controller: return try container.encode(2)
      case .sparkDriver: return try container.encode(3)
      case .sparkExecutor: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.GkeNodePoolTarget"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
