// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The configuration of a GKE node pool used by a [Dataproc-on-GKE
/// cluster](https://cloud.google.com/dataproc/docs/concepts/jobs/dataproc-gke#create-a-dataproc-on-gke-cluster).
public struct GkeNodePoolConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The node pool configuration.
  public var config: GkeNodePoolConfig.GkeNodeConfig? = nil

  /// Optional. The list of Compute Engine
  /// [zones](https://cloud.google.com/compute/docs/zones#available) where
  /// node pool nodes associated with a Dataproc on GKE virtual cluster
  /// will be located.
  ///
  /// **Note:** All node pools associated with a virtual cluster
  /// must be located in the same region as the virtual cluster, and they must
  /// be located in the same zone within that region.
  ///
  /// If a location is not specified during node pool creation, Dataproc on GKE
  /// will choose the zone.
  public var locations: [Swift.String] = []

  /// Optional. The autoscaler configuration for this node pool. The autoscaler
  /// is enabled only when a valid configuration is present.
  public var autoscaling: GkeNodePoolConfig.GkeNodePoolAutoscalingConfig? = nil

  /// Initialize a new instance of `GkeNodePoolConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GkeNodePoolConfig().with { $0.config = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Parameters that describe cluster nodes.
  public struct GkeNodeConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The name of a Compute Engine [machine
    /// type](https://cloud.google.com/compute/docs/machine-types).
    public var machineType: Swift.String = Swift.String()

    /// Optional. The number of local SSD disks to attach to the node, which is
    /// limited by the maximum number of disks allowable per zone (see [Adding
    /// Local SSDs](https://cloud.google.com/compute/docs/disks/local-ssd)).
    public var localSsdCount: Swift.Int32 = Swift.Int32()

    /// Optional. Whether the nodes are created as legacy [preemptible VM
    /// instances] (https://cloud.google.com/compute/docs/instances/preemptible).
    /// Also see
    /// [Spot][google.cloud.dataproc.v1.GkeNodePoolConfig.GkeNodeConfig.spot]
    /// VMs, preemptible VM instances without a maximum lifetime. Legacy and Spot
    /// preemptible nodes cannot be used in a node pool with the `CONTROLLER`
    /// [role]
    /// (/dataproc/docs/reference/rest/v1/projects.regions.clusters#role)
    /// or in the DEFAULT node pool if the CONTROLLER role is not assigned (the
    /// DEFAULT node pool will assume the CONTROLLER role).
    ///
    /// [google.cloud.dataproc.v1.GkeNodePoolConfig.GkeNodeConfig.spot]: <doc:GkeNodePoolConfig/GkeNodeConfig/spot>
    public var preemptible: Swift.Bool = Swift.Bool()

    /// Optional. A list of [hardware
    /// accelerators](https://cloud.google.com/compute/docs/gpus) to attach to
    /// each node.
    public var accelerators: [GkeNodePoolConfig.GkeNodePoolAcceleratorConfig] = []

    /// Optional. [Minimum CPU
    /// platform](https://cloud.google.com/compute/docs/instances/specify-min-cpu-platform)
    /// to be used by this instance. The instance may be scheduled on the
    /// specified or a newer CPU platform. Specify the friendly names of CPU
    /// platforms, such as "Intel Haswell"` or Intel Sandy Bridge".
    public var minCpuPlatform: Swift.String = Swift.String()

    /// Optional. The [Customer Managed Encryption Key (CMEK)]
    /// (https://cloud.google.com/kubernetes-engine/docs/how-to/using-cmek)
    /// used to encrypt the boot disk attached to each node in the node pool.
    /// Specify the key using the following format:
    /// `projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}`
    public var bootDiskKmsKey: Swift.String = Swift.String()

    /// Optional. Whether the nodes are created as [Spot VM instances]
    /// (https://cloud.google.com/compute/docs/instances/spot).
    /// Spot VMs are the latest update to legacy
    /// [preemptible
    /// VMs][google.cloud.dataproc.v1.GkeNodePoolConfig.GkeNodeConfig.preemptible].
    /// Spot VMs do not have a maximum lifetime. Legacy and Spot preemptible
    /// nodes cannot be used in a node pool with the `CONTROLLER`
    /// [role](/dataproc/docs/reference/rest/v1/projects.regions.clusters#role)
    /// or in the DEFAULT node pool if the CONTROLLER role is not assigned (the
    /// DEFAULT node pool will assume the CONTROLLER role).
    ///
    /// [google.cloud.dataproc.v1.GkeNodePoolConfig.GkeNodeConfig.preemptible]: <doc:GkeNodePoolConfig/GkeNodeConfig/preemptible>
    public var spot: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `GkeNodeConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GkeNodeConfig().with { $0.machineType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataproc.v1.GkeNodePoolConfig.GkeNodeConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A GkeNodeConfigAcceleratorConfig represents a Hardware Accelerator request
  /// for a node pool.
  public struct GkeNodePoolAcceleratorConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The number of accelerator cards exposed to an instance.
    public var acceleratorCount: Swift.Int64 = Swift.Int64()

    /// The accelerator type resource namename (see GPUs on Compute Engine).
    public var acceleratorType: Swift.String = Swift.String()

    /// Size of partitions to create on the GPU. Valid values are described in
    /// the NVIDIA [mig user
    /// guide](https://docs.nvidia.com/datacenter/tesla/mig-user-guide/#partitioning).
    public var gpuPartitionSize: Swift.String = Swift.String()

    /// Initialize a new instance of `GkeNodePoolAcceleratorConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GkeNodePoolAcceleratorConfig().with { $0.acceleratorCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.dataproc.v1.GkeNodePoolConfig.GkeNodePoolAcceleratorConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// GkeNodePoolAutoscaling contains information the cluster autoscaler needs to
  /// adjust the size of the node pool to the current cluster usage.
  public struct GkeNodePoolAutoscalingConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The minimum number of nodes in the node pool. Must be >= 0 and <=
    /// max_node_count.
    public var minNodeCount: Swift.Int32 = Swift.Int32()

    /// The maximum number of nodes in the node pool. Must be >= min_node_count,
    /// and must be > 0.
    /// **Note:** Quota must be sufficient to scale up the cluster.
    public var maxNodeCount: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `GkeNodePoolAutoscalingConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GkeNodePoolAutoscalingConfig().with { $0.minNodeCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.dataproc.v1.GkeNodePoolConfig.GkeNodePoolAutoscalingConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.GkeNodePoolConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
