// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A Dataproc job for running [Apache Hive](https://hive.apache.org/)
/// queries on YARN.
public struct HiveJob: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Whether to continue executing queries if a query fails.
  /// The default value is `false`. Setting to `true` can be useful when
  /// executing independent parallel queries.
  public var continueOnFailure: Swift.Bool = Swift.Bool()

  /// Optional. Mapping of query variable names to values (equivalent to the
  /// Hive command: `SET name="value";`).
  public var scriptVariables: [Swift.String: Swift.String] = [:]

  /// Optional. A mapping of property names and values, used to configure Hive.
  /// Properties that conflict with values set by the Dataproc API might be
  /// overwritten. Can include properties set in `/etc/hadoop/conf/*-site.xml`,
  /// /etc/hive/conf/hive-site.xml, and classes in user code.
  public var properties: [Swift.String: Swift.String] = [:]

  /// Optional. HCFS URIs of jar files to add to the CLASSPATH of the
  /// Hive server and Hadoop MapReduce (MR) tasks. Can contain Hive SerDes
  /// and UDFs.
  public var jarFileUris: [Swift.String] = []

  /// Required. The sequence of Hive queries to execute, specified as either
  /// an HCFS file URI or a list of queries.
  public var queries: OneOf_Queries? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `HiveJob`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HiveJob().with { $0.queryFileUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let queryFileUri = CodingKeys(stringValue: "queryFileUri")
    static let queryList = CodingKeys(stringValue: "queryList")
    static let continueOnFailure = CodingKeys(stringValue: "continueOnFailure")
    static let scriptVariables = CodingKeys(stringValue: "scriptVariables")
    static let properties = CodingKeys(stringValue: "properties")
    static let jarFileUris = CodingKeys(stringValue: "jarFileUris")

    static let _knownKeys: Set<Swift.String> = [
      "queryFileUri",
      "queryList",
      "continueOnFailure",
      "scriptVariables",
      "properties",
      "jarFileUris",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .continueOnFailure) {
      self.continueOnFailure = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .scriptVariables)
    {
      self.scriptVariables = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .properties)
    {
      self.properties = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .jarFileUris) {
      self.jarFileUris = value
    }

    var queries: OneOf_Queries? = nil
    let queriesCheckAndSet = {
      if queries != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'queries'"))
      }
      queries = $0
    }
    if let queryFileUri = try container.decodeIfPresent(Swift.String.self, forKey: .queryFileUri) {
      try queriesCheckAndSet(.queryFileUri(queryFileUri))
    }
    if let queryList = try container.decodeIfPresent(QueryList?.self, forKey: .queryList) {
      try queriesCheckAndSet(.queryList(queryList))
    }
    self.queries = queries
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.continueOnFailure, forKey: .continueOnFailure)
    try container.encode(self.scriptVariables, forKey: .scriptVariables)
    try container.encode(self.properties, forKey: .properties)
    try container.encode(self.jarFileUris, forKey: .jarFileUris)

    if let choice = self.queries {
      switch choice {
      case .queryFileUri(let value):
        try container.encode(value, forKey: .queryFileUri)
      case .queryList(let value):
        try container.encode(value, forKey: .queryList)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Required. The sequence of Hive queries to execute, specified as either
  /// an HCFS file URI or a list of queries.
  public enum OneOf_Queries: Codable, Equatable, Sendable {
    /// The HCFS URI of the script that contains Hive queries.
    case queryFileUri(Swift.String)
    /// A list of queries.
    indirect case queryList(QueryList?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.HiveJob"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
