// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A reference to a Compute Engine instance.
public struct InstanceReference: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The user-friendly name of the Compute Engine instance.
  public var instanceName: Swift.String = Swift.String()

  /// The unique identifier of the Compute Engine instance.
  public var instanceId: Swift.String = Swift.String()

  /// The public RSA key used for sharing data with this instance.
  public var publicKey: Swift.String = Swift.String()

  /// The public ECIES key used for sharing data with this instance.
  public var publicEciesKey: Swift.String = Swift.String()

  /// Initialize a new instance of `InstanceReference`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InstanceReference().with { $0.instanceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.InstanceReference"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
