// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The config settings for Compute Engine resources in
/// an instance group, such as a master or worker group.
public struct InstanceGroupConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The number of VM instances in the instance group.
  /// For [HA
  /// cluster](/dataproc/docs/concepts/configuring-clusters/high-availability)
  /// [master_config](#FIELDS.master_config) groups, **must be set to 3**.
  /// For standard cluster [master_config](#FIELDS.master_config) groups,
  /// **must be set to 1**.
  public var numInstances: Swift.Int32 = Swift.Int32()

  /// Output only. The list of instance names. Dataproc derives the names
  /// from `cluster_name`, `num_instances`, and the instance group.
  public var instanceNames: [Swift.String] = []

  /// Output only. List of references to Compute Engine instances.
  public var instanceReferences: [InstanceReference] = []

  /// Optional. The Compute Engine image resource used for cluster instances.
  ///
  /// The URI can represent an image or image family.
  ///
  /// Image examples:
  ///
  /// * `https://www.googleapis.com/compute/v1/projects/[project_id]/global/images/[image-id]`
  /// * `projects/[project_id]/global/images/[image-id]`
  /// * `image-id`
  ///
  /// Image family examples. Dataproc will use the most recent
  /// image from the family:
  ///
  /// * `https://www.googleapis.com/compute/v1/projects/[project_id]/global/images/family/[custom-image-family-name]`
  /// * `projects/[project_id]/global/images/family/[custom-image-family-name]`
  ///
  /// If the URI is unspecified, it will be inferred from
  /// `SoftwareConfig.image_version` or the system default.
  public var imageUri: Swift.String = Swift.String()

  /// Optional. The Compute Engine machine type used for cluster instances.
  ///
  /// A full URL, partial URI, or short name are valid. Examples:
  ///
  /// * `https://www.googleapis.com/compute/v1/projects/[project_id]/zones/[zone]/machineTypes/n1-standard-2`
  /// * `projects/[project_id]/zones/[zone]/machineTypes/n1-standard-2`
  /// * `n1-standard-2`
  ///
  /// **Auto Zone Exception**: If you are using the Dataproc
  /// [Auto Zone
  /// Placement](https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/auto-zone#using_auto_zone_placement)
  /// feature, you must use the short name of the machine type
  /// resource, for example, `n1-standard-2`.
  public var machineTypeUri: Swift.String = Swift.String()

  /// Optional. Disk option config settings.
  public var diskConfig: DiskConfig? = nil

  /// Output only. Specifies that this instance group contains preemptible
  /// instances.
  public var isPreemptible: Swift.Bool = Swift.Bool()

  /// Optional. Specifies the preemptibility of the instance group.
  ///
  /// The default value for master and worker groups is
  /// `NON_PREEMPTIBLE`. This default cannot be changed.
  ///
  /// The default value for secondary instances is
  /// `PREEMPTIBLE`.
  public var preemptibility: InstanceGroupConfig.Preemptibility =
    InstanceGroupConfig.Preemptibility()

  /// Output only. The config for Compute Engine Instance Group
  /// Manager that manages this group.
  /// This is only used for preemptible instance groups.
  public var managedGroupConfig: ManagedGroupConfig? = nil

  /// Optional. The Compute Engine accelerator configuration for these
  /// instances.
  public var accelerators: [AcceleratorConfig] = []

  /// Optional. Specifies the minimum cpu platform for the Instance Group.
  /// See [Dataproc -> Minimum CPU
  /// Platform](https://cloud.google.com/dataproc/docs/concepts/compute/dataproc-min-cpu).
  public var minCpuPlatform: Swift.String = Swift.String()

  /// Optional. The minimum number of primary worker instances to create.
  /// If `min_num_instances` is set, cluster creation will succeed if
  /// the number of primary workers created is at least equal to the
  /// `min_num_instances` number.
  ///
  /// Example: Cluster creation request with `num_instances` = `5` and
  /// `min_num_instances` = `3`:
  ///
  /// *  If 4 VMs are created and 1 instance fails,
  ///    the failed VM is deleted. The cluster is
  ///    resized to 4 instances and placed in a `RUNNING` state.
  /// *  If 2 instances are created and 3 instances fail,
  ///    the cluster in placed in an `ERROR` state. The failed VMs
  ///    are not deleted.
  public var minNumInstances: Swift.Int32 = Swift.Int32()

  /// Optional. Instance flexibility Policy allowing a mixture of VM shapes and
  /// provisioning models.
  public var instanceFlexibilityPolicy: InstanceFlexibilityPolicy? = nil

  /// Optional. Configuration to handle the startup of instances during cluster
  /// create and update process.
  public var startupConfig: StartupConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `InstanceGroupConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InstanceGroupConfig().with { $0.numInstances = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let numInstances = CodingKeys(stringValue: "numInstances")
    static let instanceNames = CodingKeys(stringValue: "instanceNames")
    static let instanceReferences = CodingKeys(stringValue: "instanceReferences")
    static let imageUri = CodingKeys(stringValue: "imageUri")
    static let machineTypeUri = CodingKeys(stringValue: "machineTypeUri")
    static let diskConfig = CodingKeys(stringValue: "diskConfig")
    static let isPreemptible = CodingKeys(stringValue: "isPreemptible")
    static let preemptibility = CodingKeys(stringValue: "preemptibility")
    static let managedGroupConfig = CodingKeys(stringValue: "managedGroupConfig")
    static let accelerators = CodingKeys(stringValue: "accelerators")
    static let minCpuPlatform = CodingKeys(stringValue: "minCpuPlatform")
    static let minNumInstances = CodingKeys(stringValue: "minNumInstances")
    static let instanceFlexibilityPolicy = CodingKeys(stringValue: "instanceFlexibilityPolicy")
    static let startupConfig = CodingKeys(stringValue: "startupConfig")

    static let _knownKeys: Set<Swift.String> = [
      "numInstances",
      "instanceNames",
      "instanceReferences",
      "imageUri",
      "machineTypeUri",
      "diskConfig",
      "isPreemptible",
      "preemptibility",
      "managedGroupConfig",
      "accelerators",
      "minCpuPlatform",
      "minNumInstances",
      "instanceFlexibilityPolicy",
      "startupConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .numInstances) {
      self.numInstances = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .instanceNames) {
      self.instanceNames = value
    }
    if let value = try container.decodeIfPresent(
      [InstanceReference].self, forKey: .instanceReferences)
    {
      self.instanceReferences = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .imageUri) {
      self.imageUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .machineTypeUri) {
      self.machineTypeUri = value
    }
    self.diskConfig = try container.decodeIfPresent(DiskConfig.self, forKey: .diskConfig)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isPreemptible) {
      self.isPreemptible = value
    }
    if let value = try container.decodeIfPresent(
      InstanceGroupConfig.Preemptibility.self, forKey: .preemptibility)
    {
      self.preemptibility = value
    }
    self.managedGroupConfig = try container.decodeIfPresent(
      ManagedGroupConfig.self, forKey: .managedGroupConfig)
    if let value = try container.decodeIfPresent([AcceleratorConfig].self, forKey: .accelerators) {
      self.accelerators = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .minCpuPlatform) {
      self.minCpuPlatform = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .minNumInstances) {
      self.minNumInstances = value
    }
    self.instanceFlexibilityPolicy = try container.decodeIfPresent(
      InstanceFlexibilityPolicy.self, forKey: .instanceFlexibilityPolicy)
    self.startupConfig = try container.decodeIfPresent(StartupConfig.self, forKey: .startupConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.numInstances, forKey: .numInstances)
    try container.encode(self.instanceNames, forKey: .instanceNames)
    try container.encode(self.instanceReferences, forKey: .instanceReferences)
    try container.encode(self.imageUri, forKey: .imageUri)
    try container.encode(self.machineTypeUri, forKey: .machineTypeUri)
    try container.encodeIfPresent(self.diskConfig, forKey: .diskConfig)
    try container.encode(self.isPreemptible, forKey: .isPreemptible)
    try container.encode(self.preemptibility, forKey: .preemptibility)
    try container.encodeIfPresent(self.managedGroupConfig, forKey: .managedGroupConfig)
    try container.encode(self.accelerators, forKey: .accelerators)
    try container.encode(self.minCpuPlatform, forKey: .minCpuPlatform)
    try container.encode(self.minNumInstances, forKey: .minNumInstances)
    try container.encodeIfPresent(
      self.instanceFlexibilityPolicy, forKey: .instanceFlexibilityPolicy)
    try container.encodeIfPresent(self.startupConfig, forKey: .startupConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Controls the use of preemptible instances within the group.
  public enum Preemptibility: Codable, Equatable, Sendable {
    /// Preemptibility is unspecified, the system will choose the
    /// appropriate setting for each instance group.
    case unspecified
    /// Instances are non-preemptible.
    ///
    /// This option is allowed for all instance groups and is the only valid
    /// value for Master and Worker instance groups.
    case nonPreemptible
    /// Instances are [preemptible]
    /// (https://cloud.google.com/compute/docs/instances/preemptible).
    ///
    /// This option is allowed only for [secondary worker]
    /// (https://cloud.google.com/dataproc/docs/concepts/compute/secondary-vms)
    /// groups.
    case preemptible
    /// Instances are [Spot VMs]
    /// (https://cloud.google.com/compute/docs/instances/spot).
    ///
    /// This option is allowed only for [secondary worker]
    /// (https://cloud.google.com/dataproc/docs/concepts/compute/secondary-vms)
    /// groups. Spot VMs are the latest version of [preemptible VMs]
    /// (https://cloud.google.com/compute/docs/instances/preemptible), and
    /// provide additional features.
    case spot
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .nonPreemptible: return 1
      case .preemptible: return 2
      case .spot: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PREEMPTIBILITY_UNSPECIFIED"
      case .nonPreemptible: return "NON_PREEMPTIBLE"
      case .preemptible: return "PREEMPTIBLE"
      case .spot: return "SPOT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Preemptibility/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PREEMPTIBILITY_UNSPECIFIED": self = .unspecified
      case "NON_PREEMPTIBLE": self = .nonPreemptible
      case "PREEMPTIBLE": self = .preemptible
      case "SPOT": self = .spot
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Preemptibility/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .nonPreemptible
      case 2: self = .preemptible
      case 3: self = .spot
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PREEMPTIBILITY_UNSPECIFIED")
      case .nonPreemptible: return try container.encode("NON_PREEMPTIBLE")
      case .preemptible: return try container.encode("PREEMPTIBLE")
      case .spot: return try container.encode("SPOT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.InstanceGroupConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
