// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// The JobController provides methods to manage jobs.
///
/// @Snippet(path: "JobControllerQuickstart")
public class JobControllerClient: Clients.JobControllerProtocol {
  let inner: any Clients.JobControllerStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `JobControllerClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.JobControllerStub = try Clients.JobControllerTransport(options)
    inner = Clients.JobControllerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.JobControllerLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Submits a job to a cluster.
  ///
  /// @Snippet(path: "JobController_SubmitJob")
  public func submitJob(
    request: SubmitJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDataprocV1.Job {
    try await self.inner.submitJob(request: request, options: options)
  }

  /// Submits job to a cluster.
  ///
  /// @Snippet(path: "JobController_SubmitJobAsOperation")
  public func submitJobAsOperation(
    request: SubmitJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.submitJobAsOperation(request: request, options: options)
  }

  /// Submits job to a cluster.
  ///
  /// @Snippet(path: "JobController_SubmitJobAsOperation")
  public func submitJobAsOperation(
    withPolling: SubmitJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Job> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Job>.State
      in
      return try op._extractStatus(Job.self)
    }
    let rawOp = try await self.submitJobAsOperation(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Job>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets the resource representation for a job in a project.
  ///
  /// @Snippet(path: "JobController_GetJob")
  public func getJob(
    request: GetJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDataprocV1.Job {
    try await self.inner.getJob(request: request, options: options)
  }

  /// Lists regions/{region}/jobs in a project.
  ///
  /// @Snippet(path: "JobController_ListJobs")
  public func listJobs(
    request: ListJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDataprocV1.ListJobsResponse {
    try await self.inner.listJobs(request: request, options: options)
  }

  /// Lists regions/{region}/jobs in a project.
  ///
  /// @Snippet(path: "JobController_ListJobs")
  public func listJobs(
    byItem: ListJobsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Job, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudDataprocV1.ListJobsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listJobs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Updates a job in a project.
  ///
  /// @Snippet(path: "JobController_UpdateJob")
  public func updateJob(
    request: UpdateJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDataprocV1.Job {
    try await self.inner.updateJob(request: request, options: options)
  }

  /// Starts a job cancellation request. To access the job resource
  /// after cancellation, call
  /// [regions/{region}/jobs.list](https://cloud.google.com/dataproc/docs/reference/rest/v1/projects.regions.jobs/list)
  /// or
  /// [regions/{region}/jobs.get](https://cloud.google.com/dataproc/docs/reference/rest/v1/projects.regions.jobs/get).
  ///
  /// @Snippet(path: "JobController_CancelJob")
  public func cancelJob(
    request: CancelJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDataprocV1.Job {
    try await self.inner.cancelJob(request: request, options: options)
  }

  /// Deletes the job from the project. If the job is active, the delete fails,
  /// and the response returns `FAILED_PRECONDITION`.
  ///
  /// @Snippet(path: "JobController_DeleteJob")
  public func deleteJob(
    request: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteJob(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "JobController_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "JobController_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "JobController_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "JobController_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "JobController_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "JobController_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "JobController_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "JobController_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `JobControllerClient`.
  ///
  /// To mock `JobControllerClient` change your functions to receive
  /// `some JobControllerProtocol` or `any JobControllerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol JobControllerProtocol {
    /// See `JobControllerClient.submitJob`.
    func submitJob(request: SubmitJobRequest) async throws -> GoogleCloudDataprocV1.Job

    /// See `JobControllerClient.submitJob`.
    func submitJob(
      projectId: Swift.String,
      region: Swift.String,
      job: Job?,
    ) async throws -> GoogleCloudDataprocV1.Job

    /// See `JobControllerClient.submitJobAsOperation`.
    func submitJobAsOperation(request: SubmitJobRequest) async throws -> GoogleLongRunning.Operation

    /// See `JobControllerClient.submitJobAsOperation`.
    func submitJobAsOperation(withPolling: SubmitJobRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Job>

    /// See `JobControllerClient.submitJobAsOperation`.
    func submitJobAsOperation(
      projectId: Swift.String,
      region: Swift.String,
      job: Job?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Job>

    /// See `JobControllerClient.getJob`.
    func getJob(request: GetJobRequest) async throws -> GoogleCloudDataprocV1.Job

    /// See `JobControllerClient.getJob`.
    func getJob(
      projectId: Swift.String,
      region: Swift.String,
      jobId: Swift.String,
    ) async throws -> GoogleCloudDataprocV1.Job

    /// See `JobControllerClient.listJobs`.
    func listJobs(request: ListJobsRequest) async throws -> GoogleCloudDataprocV1.ListJobsResponse

    /// See `JobControllerClient.listJobs`.
    func listJobs(
      byItem: ListJobsRequest
    ) throws -> any AsyncSequence<Job, Swift.Error>

    /// See `JobControllerClient.listJobs`.
    func listJobs(
      projectId: Swift.String,
      region: Swift.String,
    ) throws -> any AsyncSequence<Job, Swift.Error>

    /// See `JobControllerClient.listJobs`.
    func listJobs(
      projectId: Swift.String,
      region: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<Job, Swift.Error>

    /// See `JobControllerClient.updateJob`.
    func updateJob(request: UpdateJobRequest) async throws -> GoogleCloudDataprocV1.Job

    /// See `JobControllerClient.cancelJob`.
    func cancelJob(request: CancelJobRequest) async throws -> GoogleCloudDataprocV1.Job

    /// See `JobControllerClient.cancelJob`.
    func cancelJob(
      projectId: Swift.String,
      region: Swift.String,
      jobId: Swift.String,
    ) async throws -> GoogleCloudDataprocV1.Job

    /// See `JobControllerClient.deleteJob`.
    func deleteJob(request: DeleteJobRequest) async throws

    /// See `JobControllerClient.deleteJob`.
    func deleteJob(
      projectId: Swift.String,
      region: Swift.String,
      jobId: Swift.String,
    ) async throws

    /// See `JobControllerClient.setIamPolicy`.
    func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `JobControllerClient.getIamPolicy`.
    func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `JobControllerClient.testIamPermissions`.
    func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
      -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `JobControllerClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `JobControllerClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `JobControllerClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `JobControllerClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `JobControllerClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `JobControllerClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `JobControllerClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `JobControllerClient.submitJob`.
    func submitJob(
      request: SubmitJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.Job

    /// See `JobControllerClient.submitJobAsOperation`.
    func submitJobAsOperation(
      request: SubmitJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `JobControllerClient.submitJobAsOperation`.
    func submitJobAsOperation(
      withPolling: SubmitJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Job>

    /// See `JobControllerClient.getJob`.
    func getJob(
      request: GetJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.Job

    /// See `JobControllerClient.listJobs`.
    func listJobs(
      request: ListJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.ListJobsResponse

    /// See `JobControllerClient.listJobs`.
    func listJobs(
      byItem: ListJobsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Job, Swift.Error>

    /// See `JobControllerClient.updateJob`.
    func updateJob(
      request: UpdateJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.Job

    /// See `JobControllerClient.cancelJob`.
    func cancelJob(
      request: CancelJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.Job

    /// See `JobControllerClient.deleteJob`.
    func deleteJob(
      request: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `JobControllerClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `JobControllerClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `JobControllerClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `JobControllerClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `JobControllerClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `JobControllerClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `JobControllerClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.JobControllerProtocol {
  public func submitJob(request: SubmitJobRequest) async throws -> GoogleCloudDataprocV1.Job {
    try await self.submitJob(request: request, options: .init())
  }

  public func submitJob(
    request: SubmitJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDataprocV1.Job {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func submitJob(
    projectId: Swift.String,
    region: Swift.String,
    job: Job?,
  ) async throws -> GoogleCloudDataprocV1.Job {
    let request = SubmitJobRequest().with {
      $0.projectId = projectId
      $0.region = region
      $0.job = job
    }
    return try await self.submitJob(request: request)
  }

  public func submitJobAsOperation(request: SubmitJobRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.submitJobAsOperation(request: request, options: .init())
  }

  public func submitJobAsOperation(
    request: SubmitJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func submitJobAsOperation(withPolling: SubmitJobRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Job>
  {
    try await self.submitJobAsOperation(withPolling: withPolling, options: .init())
  }

  public func submitJobAsOperation(
    withPolling: SubmitJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Job> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Job>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func submitJobAsOperation(
    projectId: Swift.String,
    region: Swift.String,
    job: Job?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Job> {
    let request = SubmitJobRequest().with {
      $0.projectId = projectId
      $0.region = region
      $0.job = job
    }
    return try await self.submitJobAsOperation(withPolling: request)
  }

  public func getJob(request: GetJobRequest) async throws -> GoogleCloudDataprocV1.Job {
    try await self.getJob(request: request, options: .init())
  }

  public func getJob(
    request: GetJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDataprocV1.Job {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getJob(
    projectId: Swift.String,
    region: Swift.String,
    jobId: Swift.String,
  ) async throws -> GoogleCloudDataprocV1.Job {
    let request = GetJobRequest().with {
      $0.projectId = projectId
      $0.region = region
      $0.jobId = jobId
    }
    return try await self.getJob(request: request)
  }

  public func listJobs(request: ListJobsRequest) async throws
    -> GoogleCloudDataprocV1.ListJobsResponse
  {
    try await self.listJobs(request: request, options: .init())
  }

  public func listJobs(
    request: ListJobsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDataprocV1.ListJobsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listJobs(
    byItem: ListJobsRequest
  ) throws -> any AsyncSequence<Job, Swift.Error> {
    try self.listJobs(byItem: byItem, options: .init())
  }

  public func listJobs(
    byItem: ListJobsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Job, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudDataprocV1.ListJobsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listJobs(
    projectId: Swift.String,
    region: Swift.String,
  ) throws -> any AsyncSequence<Job, Swift.Error> {
    let request = ListJobsRequest().with {
      $0.projectId = projectId
      $0.region = region
    }
    return try self.listJobs(byItem: request)
  }

  public func listJobs(
    projectId: Swift.String,
    region: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<Job, Swift.Error> {
    let request = ListJobsRequest().with {
      $0.projectId = projectId
      $0.region = region
      $0.filter = filter
    }
    return try self.listJobs(byItem: request)
  }

  public func updateJob(request: UpdateJobRequest) async throws -> GoogleCloudDataprocV1.Job {
    try await self.updateJob(request: request, options: .init())
  }

  public func updateJob(
    request: UpdateJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDataprocV1.Job {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelJob(request: CancelJobRequest) async throws -> GoogleCloudDataprocV1.Job {
    try await self.cancelJob(request: request, options: .init())
  }

  public func cancelJob(
    request: CancelJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDataprocV1.Job {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelJob(
    projectId: Swift.String,
    region: Swift.String,
    jobId: Swift.String,
  ) async throws -> GoogleCloudDataprocV1.Job {
    let request = CancelJobRequest().with {
      $0.projectId = projectId
      $0.region = region
      $0.jobId = jobId
    }
    return try await self.cancelJob(request: request)
  }

  public func deleteJob(request: DeleteJobRequest) async throws {
    try await self.deleteJob(request: request, options: .init())
  }

  public func deleteJob(
    request: DeleteJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteJob(
    projectId: Swift.String,
    region: Swift.String,
    jobId: Swift.String,
  ) async throws {
    let request = DeleteJobRequest().with {
      $0.projectId = projectId
      $0.region = region
      $0.jobId = jobId
    }
    try await self.deleteJob(request: request)
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
