// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol JobControllerStub: Sendable {
    func submitJob(
      request: SubmitJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.Job

    func submitJobAsOperation(
      request: SubmitJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getJob(
      request: GetJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.Job

    func listJobs(
      request: ListJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.ListJobsResponse

    func updateJob(
      request: UpdateJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.Job

    func cancelJob(
      request: CancelJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.Job

    func deleteJob(
      request: DeleteJobRequest, options: GoogleGax.RequestOptions
    ) async throws

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
