// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A request to list sessions in a project.
public struct ListSessionsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent, which owns this collection of sessions.
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of sessions to return in each response.
  /// The service may return fewer than this value.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token received from a previous `ListSessions` call.
  /// Provide this token to retrieve the subsequent page.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. A filter for the sessions to return in the response.
  ///
  /// A filter is a logical expression constraining the values of various fields
  /// in each session resource. Filters are case sensitive, and may contain
  /// multiple clauses combined with logical operators (AND, OR).
  /// Supported fields are `session_id`, `session_uuid`, `state`, `create_time`,
  /// and `labels`.
  ///
  /// Example: `state = ACTIVE and create_time < "2023-01-01T00:00:00Z"`
  /// is a filter for sessions in an ACTIVE state that were created before
  /// 2023-01-01. `state = ACTIVE and labels.environment=production` is a filter
  /// for sessions in an ACTIVE state that have a production environment label.
  ///
  /// See https://google.aip.dev/assets/misc/ebnf-filtering.txt for a detailed
  /// description of the filter syntax and a list of supported comparators.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListSessionsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListSessionsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.ListSessionsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
