// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A request to list jobs in a project.
public struct ListJobsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The ID of the Google Cloud Platform project that the job
  /// belongs to.
  public var projectId: Swift.String = Swift.String()

  /// Required. The Dataproc region in which to handle the request.
  public var region: Swift.String = Swift.String()

  /// Optional. The number of results to return in each response.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The page token, returned by a previous call, to request the
  /// next page of results.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. If set, the returned jobs list includes only jobs that were
  /// submitted to the named cluster.
  public var clusterName: Swift.String = Swift.String()

  /// Optional. Specifies enumerated categories of jobs to list.
  /// (default = match ALL jobs).
  ///
  /// If `filter` is provided, `jobStateMatcher` will be ignored.
  public var jobStateMatcher: ListJobsRequest.JobStateMatcher = ListJobsRequest.JobStateMatcher()

  /// Optional. A filter constraining the jobs to list. Filters are
  /// case-sensitive and have the following syntax:
  ///
  /// [field = value] AND [field [= value]] ...
  ///
  /// where **field** is `status.state` or `insertTime`, or `labels.[KEY]`, and
  /// `[KEY]` is a label key. **value** can be `*` to match all values.
  /// `status.state` can be either `ACTIVE` or `NON_ACTIVE`.
  /// Allows `insertTime` to be a timestamp in RFC 3339 format in double quotes,
  /// such as `2025-01-01T00:00:00Z`. Only the logical `AND` operator is
  /// supported; space-separated items are treated as having an implicit `AND`
  /// operator.
  ///
  /// Example filter:
  ///
  /// status.state = ACTIVE AND labels.env = staging AND labels.starred = * AND
  /// insertTime <= "2025-01-01T00:00:00Z"
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListJobsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListJobsRequest().with { $0.projectId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A matcher that specifies categories of job states.
  public enum JobStateMatcher: Codable, Equatable, Sendable {
    /// Match all jobs, regardless of state.
    case all
    /// Only match jobs in non-terminal states: PENDING, RUNNING, or
    /// CANCEL_PENDING.
    case active
    /// Only match jobs in terminal states: CANCELLED, DONE, or ERROR.
    case nonActive
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .all
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .all: return 0
      case .active: return 1
      case .nonActive: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .all: return "ALL"
      case .active: return "ACTIVE"
      case .nonActive: return "NON_ACTIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:JobStateMatcher/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ALL": self = .all
      case "ACTIVE": self = .active
      case "NON_ACTIVE": self = .nonActive
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:JobStateMatcher/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .all
      case 1: self = .active
      case 2: self = .nonActive
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .all: return try container.encode(0)
      case .active: return try container.encode(1)
      case .nonActive: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.ListJobsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
