// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A request to list batch workloads in a project.
public struct ListBatchesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent, which owns this collection of batches.
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of batches to return in each response.
  /// The service may return fewer than this value.
  /// The default page size is 20; the maximum page size is 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token received from a previous `ListBatches` call.
  /// Provide this token to retrieve the subsequent page.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. A filter for the batches to return in the response.
  ///
  /// A filter is a logical expression constraining the values of various fields
  /// in each batch resource. Filters are case sensitive, and may contain
  /// multiple clauses combined with logical operators (AND/OR).
  /// Supported fields are `batch_id`, `batch_uuid`, `state`, `create_time`, and
  /// `labels`.
  ///
  /// e.g. `state = RUNNING and create_time < "2023-01-01T00:00:00Z"`
  /// filters for batches in state RUNNING that were created before 2023-01-01.
  /// `state = RUNNING and labels.environment=production` filters for batches in
  /// state in a RUNNING state that have a production environment label.
  ///
  /// See https://google.aip.dev/assets/misc/ebnf-filtering.txt for a detailed
  /// description of the filter syntax and a list of supported comparisons.
  public var filter: Swift.String = Swift.String()

  /// Optional. Field(s) on which to sort the list of batches.
  ///
  /// Currently the only supported sort orders are unspecified (empty) and
  /// `create_time desc` to sort by most recently created batches first.
  ///
  /// See https://google.aip.dev/132#ordering for more details.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListBatchesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListBatchesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.ListBatchesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
