// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Specifies an executable to run on a fully configured node and a
/// timeout period for executable completion.
public struct NodeInitializationAction: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Cloud Storage URI of executable file.
  public var executableFile: Swift.String = Swift.String()

  /// Optional. Amount of time executable has to complete. Default is
  /// 10 minutes (see JSON representation of
  /// [Duration](https://developers.google.com/protocol-buffers/docs/proto3#json)).
  ///
  /// Cluster creation fails with an explanatory error message (the
  /// name of the executable that caused the error and the exceeded timeout
  /// period) if the executable is not completed at end of the timeout period.
  public var executionTimeout: GoogleCloudWKT.Duration? = nil

  /// Initialize a new instance of `NodeInitializationAction`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NodeInitializationAction().with { $0.executableFile = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.NodeInitializationAction"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
