// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Runtime information about workload execution.
public struct RuntimeInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Map of remote access endpoints (such as web interfaces and
  /// APIs) to their URIs.
  public var endpoints: [Swift.String: Swift.String] = [:]

  /// Output only. A URI pointing to the location of the stdout and stderr of the
  /// workload.
  public var outputUri: Swift.String = Swift.String()

  /// Output only. A URI pointing to the location of the diagnostics tarball.
  public var diagnosticOutputUri: Swift.String = Swift.String()

  /// Output only. Approximate workload resource usage, calculated when
  /// the workload completes (see [Dataproc Serverless pricing]
  /// (https://cloud.google.com/dataproc-serverless/pricing)).
  ///
  /// **Note:** This metric calculation may change in the future, for
  /// example, to capture cumulative workload resource
  /// consumption during workload execution (see the
  /// [Dataproc Serverless release notes]
  /// (https://cloud.google.com/dataproc-serverless/docs/release-notes)
  /// for announcements, changes, fixes
  /// and other Dataproc developments).
  public var approximateUsage: UsageMetrics? = nil

  /// Output only. Snapshot of current workload resource usage.
  public var currentUsage: UsageSnapshot? = nil

  /// Initialize a new instance of `RuntimeInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RuntimeInfo().with { $0.endpoints = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.RuntimeInfo"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
