// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Runtime information about workload execution.
public struct RuntimeInfo: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Map of remote access endpoints (such as web interfaces and
  /// APIs) to their URIs.
  public var endpoints: [Swift.String: Swift.String] = [:]

  /// Output only. A URI pointing to the location of the stdout and stderr of the
  /// workload.
  public var outputUri: Swift.String = Swift.String()

  /// Output only. A URI pointing to the location of the diagnostics tarball.
  public var diagnosticOutputUri: Swift.String = Swift.String()

  /// Output only. Approximate workload resource usage, calculated when
  /// the workload completes (see [Dataproc Serverless pricing]
  /// (https://cloud.google.com/dataproc-serverless/pricing)).
  ///
  /// **Note:** This metric calculation may change in the future, for
  /// example, to capture cumulative workload resource
  /// consumption during workload execution (see the
  /// [Dataproc Serverless release notes]
  /// (https://cloud.google.com/dataproc-serverless/docs/release-notes)
  /// for announcements, changes, fixes
  /// and other Dataproc developments).
  public var approximateUsage: UsageMetrics? = nil

  /// Output only. Snapshot of current workload resource usage.
  public var currentUsage: UsageSnapshot? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RuntimeInfo`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RuntimeInfo().with { $0.endpoints = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let endpoints = CodingKeys(stringValue: "endpoints")
    static let outputUri = CodingKeys(stringValue: "outputUri")
    static let diagnosticOutputUri = CodingKeys(stringValue: "diagnosticOutputUri")
    static let approximateUsage = CodingKeys(stringValue: "approximateUsage")
    static let currentUsage = CodingKeys(stringValue: "currentUsage")

    static let _knownKeys: Set<Swift.String> = [
      "endpoints",
      "outputUri",
      "diagnosticOutputUri",
      "approximateUsage",
      "currentUsage",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .endpoints)
    {
      self.endpoints = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .outputUri) {
      self.outputUri = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .diagnosticOutputUri) {
      self.diagnosticOutputUri = value
    }
    self.approximateUsage = try container.decodeIfPresent(
      UsageMetrics.self, forKey: .approximateUsage)
    self.currentUsage = try container.decodeIfPresent(UsageSnapshot.self, forKey: .currentUsage)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.endpoints, forKey: .endpoints)
    try container.encode(self.outputUri, forKey: .outputUri)
    try container.encode(self.diagnosticOutputUri, forKey: .diagnosticOutputUri)
    try container.encodeIfPresent(self.approximateUsage, forKey: .approximateUsage)
    try container.encodeIfPresent(self.currentUsage, forKey: .currentUsage)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.RuntimeInfo"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
