// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Runtime configuration for a workload.
public struct RuntimeConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Version of the batch runtime.
  public var version: Swift.String = Swift.String()

  /// Optional. Optional custom container image for the job runtime environment.
  /// If not specified, a default container image will be used.
  public var containerImage: Swift.String = Swift.String()

  /// Optional. A mapping of property names to values, which are used to
  /// configure workload execution.
  public var properties: [Swift.String: Swift.String] = [:]

  /// Optional. Dependency repository configuration.
  public var repositoryConfig: RepositoryConfig? = nil

  /// Optional. Autotuning configuration of the workload.
  public var autotuningConfig: AutotuningConfig? = nil

  /// Optional. Cohort identifier. Identifies families of the workloads that have
  /// the same shape, for example, daily ETL jobs.
  public var cohort: Swift.String = Swift.String()

  /// Initialize a new instance of `RuntimeConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RuntimeConfig().with { $0.version = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.RuntimeConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
