// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class SessionTemplateControllerLogging: SessionTemplateControllerStub {
    let inner: any SessionTemplateControllerStub
    let logger: Logger

    public init(_ inner: any SessionTemplateControllerStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-dataproc-v1"
      logger[metadataKey: "gcp.client.service"] = "dataproc"
      logger[metadataKey: "gcp.experimental.swift.client"] = "SessionTemplateController"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createSessionTemplate(
      request: CreateSessionTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.SessionTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "createSessionTemplate",
        action: {
          (r: CreateSessionTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDataprocV1.SessionTemplate
          in
          return try await self.inner.createSessionTemplate(request: r, options: o)
        })
    }

    public func updateSessionTemplate(
      request: UpdateSessionTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.SessionTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSessionTemplate",
        action: {
          (r: UpdateSessionTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDataprocV1.SessionTemplate
          in
          return try await self.inner.updateSessionTemplate(request: r, options: o)
        })
    }

    public func getSessionTemplate(
      request: GetSessionTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.SessionTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSessionTemplate",
        action: {
          (r: GetSessionTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDataprocV1.SessionTemplate
          in
          return try await self.inner.getSessionTemplate(request: r, options: o)
        })
    }

    public func listSessionTemplates(
      request: ListSessionTemplatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.ListSessionTemplatesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSessionTemplates",
        action: {
          (r: ListSessionTemplatesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDataprocV1.ListSessionTemplatesResponse
          in
          return try await self.inner.listSessionTemplates(request: r, options: o)
        })
    }

    public func deleteSessionTemplate(
      request: DeleteSessionTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteSessionTemplate",
        action: {
          (r: DeleteSessionTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.deleteSessionTemplate(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
