// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Shielded Instance Config for clusters using [Compute Engine Shielded
/// VMs](https://cloud.google.com/security/shielded-cloud/shielded-vm).
public struct ShieldedInstanceConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Defines whether instances have Secure Boot enabled.
  public var enableSecureBoot: Swift.Bool? = nil

  /// Optional. Defines whether instances have the vTPM enabled.
  public var enableVtpm: Swift.Bool? = nil

  /// Optional. Defines whether instances have integrity monitoring enabled.
  public var enableIntegrityMonitoring: Swift.Bool? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ShieldedInstanceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ShieldedInstanceConfig().with { $0.enableSecureBoot = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let enableSecureBoot = CodingKeys(stringValue: "enableSecureBoot")
    static let enableVtpm = CodingKeys(stringValue: "enableVtpm")
    static let enableIntegrityMonitoring = CodingKeys(stringValue: "enableIntegrityMonitoring")

    static let _knownKeys: Set<Swift.String> = [
      "enableSecureBoot",
      "enableVtpm",
      "enableIntegrityMonitoring",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.enableSecureBoot = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableSecureBoot)
    self.enableVtpm = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableVtpm)
    self.enableIntegrityMonitoring = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .enableIntegrityMonitoring)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.enableSecureBoot, forKey: .enableSecureBoot)
    try container.encodeIfPresent(self.enableVtpm, forKey: .enableVtpm)
    try container.encodeIfPresent(
      self.enableIntegrityMonitoring, forKey: .enableIntegrityMonitoring)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.ShieldedInstanceConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
