// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Specifies the selection and config of software inside the cluster.
public struct SoftwareConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The version of software inside the cluster. It must be one of the
  /// supported [Dataproc
  /// Versions](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-versions#supported-dataproc-image-versions),
  /// such as "1.2" (including a subminor version, such as "1.2.29"), or the
  /// ["preview"
  /// version](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-versions#other_versions).
  /// If unspecified, it defaults to the latest Debian version.
  public var imageVersion: Swift.String = Swift.String()

  /// Optional. The properties to set on daemon config files.
  ///
  /// Property keys are specified in `prefix:property` format, for example
  /// `core:hadoop.tmp.dir`. The following are supported prefixes
  /// and their mappings:
  ///
  /// * capacity-scheduler: `capacity-scheduler.xml`
  /// * core:   `core-site.xml`
  /// * distcp: `distcp-default.xml`
  /// * hdfs:   `hdfs-site.xml`
  /// * hive:   `hive-site.xml`
  /// * mapred: `mapred-site.xml`
  /// * pig:    `pig.properties`
  /// * spark:  `spark-defaults.conf`
  /// * yarn:   `yarn-site.xml`
  ///
  /// For more information, see [Cluster
  /// properties](https://cloud.google.com/dataproc/docs/concepts/cluster-properties).
  public var properties: [Swift.String: Swift.String] = [:]

  /// Optional. The set of components to activate on the cluster.
  public var optionalComponents: [Component] = []

  /// Initialize a new instance of `SoftwareConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SoftwareConfig().with { $0.imageVersion = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.SoftwareConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
