// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A configuration for running
/// [Apache Spark SQL](https://spark.apache.org/sql/) queries as a batch
/// workload.
public struct SparkSqlBatch: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The HCFS URI of the script that contains Spark SQL queries to
  /// execute.
  public var queryFileUri: Swift.String = Swift.String()

  /// Optional. Mapping of query variable names to values (equivalent to the
  /// Spark SQL command: `SET name="value";`).
  public var queryVariables: [Swift.String: Swift.String] = [:]

  /// Optional. HCFS URIs of jar files to be added to the Spark CLASSPATH.
  public var jarFileUris: [Swift.String] = []

  /// Initialize a new instance of `SparkSqlBatch`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SparkSqlBatch().with { $0.queryFileUri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.SparkSqlBatch"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
