// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A configurable parameter that replaces one or more fields in the template.
/// Parameterizable fields:
/// - Labels
/// - File uris
/// - Job properties
/// - Job arguments
/// - Script variables
/// - Main class (in HadoopJob and SparkJob)
/// - Zone (in ClusterSelector)
public struct TemplateParameter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Parameter name.
  /// The parameter name is used as the key, and paired with the
  /// parameter value, which are passed to the template when the template
  /// is instantiated.
  /// The name must contain only capital letters (A-Z), numbers (0-9), and
  /// underscores (_), and must not start with a number. The maximum length is
  /// 40 characters.
  public var name: Swift.String = Swift.String()

  /// Required. Paths to all fields that the parameter replaces.
  /// A field is allowed to appear in at most one parameter's list of field
  /// paths.
  ///
  /// A field path is similar in syntax to a
  /// [google.protobuf.FieldMask][google.protobuf.FieldMask]. For example, a
  /// field path that references the zone field of a workflow template's cluster
  /// selector would be specified as `placement.clusterSelector.zone`.
  ///
  /// Also, field paths can reference fields using the following syntax:
  ///
  /// * Values in maps can be referenced by key:
  ///     * labels['key']
  ///     * placement.clusterSelector.clusterLabels['key']
  ///     * placement.managedCluster.labels['key']
  ///     * placement.clusterSelector.clusterLabels['key']
  ///     * jobs['step-id'].labels['key']
  ///
  /// * Jobs in the jobs list can be referenced by step-id:
  ///     * jobs['step-id'].hadoopJob.mainJarFileUri
  ///     * jobs['step-id'].hiveJob.queryFileUri
  ///     * jobs['step-id'].pySparkJob.mainPythonFileUri
  ///     * jobs['step-id'].hadoopJob.jarFileUris[0]
  ///     * jobs['step-id'].hadoopJob.archiveUris[0]
  ///     * jobs['step-id'].hadoopJob.fileUris[0]
  ///     * jobs['step-id'].pySparkJob.pythonFileUris[0]
  ///
  /// * Items in repeated fields can be referenced by a zero-based index:
  ///     * jobs['step-id'].sparkJob.args[0]
  ///
  /// * Other examples:
  ///     * jobs['step-id'].hadoopJob.properties['key']
  ///     * jobs['step-id'].hadoopJob.args[0]
  ///     * jobs['step-id'].hiveJob.scriptVariables['key']
  ///     * jobs['step-id'].hadoopJob.mainJarFileUri
  ///     * placement.clusterSelector.zone
  ///
  /// It may not be possible to parameterize maps and repeated fields in their
  /// entirety since only individual map values and individual items in repeated
  /// fields can be referenced. For example, the following field paths are
  /// invalid:
  ///
  /// - placement.clusterSelector.clusterLabels
  /// - jobs['step-id'].sparkJob.args
  ///
  /// [google.protobuf.FieldMask]: https://www.google.com/search?q=Swift+google.protobuf+GoogleCloudWkt.FieldMask
  public var fields: [Swift.String] = []

  /// Optional. Brief description of the parameter.
  /// Must not exceed 1024 characters.
  public var description: Swift.String = Swift.String()

  /// Optional. Validation rules to be applied to this parameter's value.
  public var validation: ParameterValidation? = nil

  /// Initialize a new instance of `TemplateParameter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TemplateParameter().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.TemplateParameter"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
