// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The usage snapshot represents the resources consumed by a workload at a
/// specified time.
public struct UsageSnapshot: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Milli (one-thousandth) Dataproc Compute Units (DCUs) (see
  /// [Dataproc Serverless pricing]
  /// (https://cloud.google.com/dataproc-serverless/pricing)).
  public var milliDcu: Swift.Int64 = Swift.Int64()

  /// Optional. Shuffle Storage in gigabytes (GB). (see [Dataproc Serverless
  /// pricing] (https://cloud.google.com/dataproc-serverless/pricing))
  public var shuffleStorageGb: Swift.Int64 = Swift.Int64()

  /// Optional. Milli (one-thousandth) Dataproc Compute Units (DCUs) charged at
  /// premium tier (see [Dataproc Serverless pricing]
  /// (https://cloud.google.com/dataproc-serverless/pricing)).
  public var milliDcuPremium: Swift.Int64 = Swift.Int64()

  /// Optional. Shuffle Storage in gigabytes (GB) charged at premium tier. (see
  /// [Dataproc Serverless pricing]
  /// (https://cloud.google.com/dataproc-serverless/pricing))
  public var shuffleStorageGbPremium: Swift.Int64 = Swift.Int64()

  /// Optional. Milli (one-thousandth) accelerator. (see [Dataproc
  /// Serverless pricing] (https://cloud.google.com/dataproc-serverless/pricing))
  public var milliAccelerator: Swift.Int64 = Swift.Int64()

  /// Optional. Accelerator type being used, if any
  public var acceleratorType: Swift.String = Swift.String()

  /// Optional. The timestamp of the usage snapshot.
  public var snapshotTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `UsageSnapshot`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UsageSnapshot().with { $0.milliDcu = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.UsageSnapshot"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
