// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class WorkflowTemplateServiceLogging: WorkflowTemplateServiceStub {
    let inner: any WorkflowTemplateServiceStub
    let logger: Logger

    public init(_ inner: any WorkflowTemplateServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-dataproc-v1"
      logger[metadataKey: "gcp.client.service"] = "dataproc"
      logger[metadataKey: "gcp.experimental.swift.client"] = "WorkflowTemplateService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createWorkflowTemplate(
      request: CreateWorkflowTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.WorkflowTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "createWorkflowTemplate",
        action: {
          (r: CreateWorkflowTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDataprocV1.WorkflowTemplate
          in
          return try await self.inner.createWorkflowTemplate(request: r, options: o)
        })
    }

    public func getWorkflowTemplate(
      request: GetWorkflowTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.WorkflowTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "getWorkflowTemplate",
        action: {
          (r: GetWorkflowTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDataprocV1.WorkflowTemplate
          in
          return try await self.inner.getWorkflowTemplate(request: r, options: o)
        })
    }

    public func instantiateWorkflowTemplate(
      request: InstantiateWorkflowTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "instantiateWorkflowTemplate",
        action: {
          (r: InstantiateWorkflowTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.instantiateWorkflowTemplate(request: r, options: o)
        })
    }

    public func instantiateInlineWorkflowTemplate(
      request: InstantiateInlineWorkflowTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "instantiateInlineWorkflowTemplate",
        action: {
          (r: InstantiateInlineWorkflowTemplateRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.Operation
          in
          return try await self.inner.instantiateInlineWorkflowTemplate(request: r, options: o)
        })
    }

    public func updateWorkflowTemplate(
      request: UpdateWorkflowTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.WorkflowTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateWorkflowTemplate",
        action: {
          (r: UpdateWorkflowTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDataprocV1.WorkflowTemplate
          in
          return try await self.inner.updateWorkflowTemplate(request: r, options: o)
        })
    }

    public func listWorkflowTemplates(
      request: ListWorkflowTemplatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataprocV1.ListWorkflowTemplatesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listWorkflowTemplates",
        action: {
          (r: ListWorkflowTemplatesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudDataprocV1.ListWorkflowTemplatesResponse
          in
          return try await self.inner.listWorkflowTemplates(request: r, options: o)
        })
    }

    public func deleteWorkflowTemplate(
      request: DeleteWorkflowTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteWorkflowTemplate",
        action: {
          (r: DeleteWorkflowTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.deleteWorkflowTemplate(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
