// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A Dataproc workflow template resource.
public struct WorkflowMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the workflow template as described
  /// in https://cloud.google.com/apis/design/resource_names.
  ///
  /// * For `projects.regions.workflowTemplates`, the resource name of the
  ///   template has the following format:
  ///   `projects/{project_id}/regions/{region}/workflowTemplates/{template_id}`
  ///
  /// * For `projects.locations.workflowTemplates`, the resource name of the
  ///   template has the following format:
  ///   `projects/{project_id}/locations/{location}/workflowTemplates/{template_id}`
  public var template: Swift.String = Swift.String()

  /// Output only. The version of template at the time of
  /// workflow instantiation.
  public var version: Swift.Int32 = Swift.Int32()

  /// Output only. The create cluster operation metadata.
  public var createCluster: ClusterOperation? = nil

  /// Output only. The workflow graph.
  public var graph: WorkflowGraph? = nil

  /// Output only. The delete cluster operation metadata.
  public var deleteCluster: ClusterOperation? = nil

  /// Output only. The workflow state.
  public var state: WorkflowMetadata.State = WorkflowMetadata.State()

  /// Output only. The name of the target cluster.
  public var clusterName: Swift.String = Swift.String()

  /// Map from parameter names to values that were used for those parameters.
  public var parameters: [Swift.String: Swift.String] = [:]

  /// Output only. Workflow start time.
  public var startTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. Workflow end time.
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The UUID of target cluster.
  public var clusterUuid: Swift.String = Swift.String()

  /// Output only. The timeout duration for the DAG of jobs, expressed in seconds
  /// (see [JSON representation of
  /// duration](https://developers.google.com/protocol-buffers/docs/proto3#json)).
  public var dagTimeout: GoogleWKT.WKTDuration? = nil

  /// Output only. DAG start time, only set for workflows with
  /// [dag_timeout][google.cloud.dataproc.v1.WorkflowMetadata.dag_timeout] when
  /// DAG begins.
  ///
  /// [google.cloud.dataproc.v1.WorkflowMetadata.dag_timeout]: <doc:WorkflowMetadata/dagTimeout>
  public var dagStartTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. DAG end time, only set for workflows with
  /// [dag_timeout][google.cloud.dataproc.v1.WorkflowMetadata.dag_timeout] when
  /// DAG ends.
  ///
  /// [google.cloud.dataproc.v1.WorkflowMetadata.dag_timeout]: <doc:WorkflowMetadata/dagTimeout>
  public var dagEndTime: GoogleWKT.WKTTimestamp? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `WorkflowMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = WorkflowMetadata().with { $0.template = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let template = CodingKeys(stringValue: "template")
    static let version = CodingKeys(stringValue: "version")
    static let createCluster = CodingKeys(stringValue: "createCluster")
    static let graph = CodingKeys(stringValue: "graph")
    static let deleteCluster = CodingKeys(stringValue: "deleteCluster")
    static let state = CodingKeys(stringValue: "state")
    static let clusterName = CodingKeys(stringValue: "clusterName")
    static let parameters = CodingKeys(stringValue: "parameters")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let clusterUuid = CodingKeys(stringValue: "clusterUuid")
    static let dagTimeout = CodingKeys(stringValue: "dagTimeout")
    static let dagStartTime = CodingKeys(stringValue: "dagStartTime")
    static let dagEndTime = CodingKeys(stringValue: "dagEndTime")

    static let _knownKeys: Set<Swift.String> = [
      "template",
      "version",
      "createCluster",
      "graph",
      "deleteCluster",
      "state",
      "clusterName",
      "parameters",
      "startTime",
      "endTime",
      "clusterUuid",
      "dagTimeout",
      "dagStartTime",
      "dagEndTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .template) {
      self.template = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .version) {
      self.version = value
    }
    self.createCluster = try container.decodeIfPresent(
      ClusterOperation.self, forKey: .createCluster)
    self.graph = try container.decodeIfPresent(WorkflowGraph.self, forKey: .graph)
    self.deleteCluster = try container.decodeIfPresent(
      ClusterOperation.self, forKey: .deleteCluster)
    if let value = try container.decodeIfPresent(WorkflowMetadata.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clusterName) {
      self.clusterName = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .parameters)
    {
      self.parameters = value
    }
    self.startTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clusterUuid) {
      self.clusterUuid = value
    }
    self.dagTimeout = try container.decodeIfPresent(GoogleWKT.WKTDuration.self, forKey: .dagTimeout)
    self.dagStartTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .dagStartTime)
    self.dagEndTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .dagEndTime)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.template, forKey: .template)
    try container.encode(self.version, forKey: .version)
    try container.encodeIfPresent(self.createCluster, forKey: .createCluster)
    try container.encodeIfPresent(self.graph, forKey: .graph)
    try container.encodeIfPresent(self.deleteCluster, forKey: .deleteCluster)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.clusterName, forKey: .clusterName)
    try container.encode(self.parameters, forKey: .parameters)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.clusterUuid, forKey: .clusterUuid)
    try container.encodeIfPresent(self.dagTimeout, forKey: .dagTimeout)
    try container.encodeIfPresent(self.dagStartTime, forKey: .dagStartTime)
    try container.encodeIfPresent(self.dagEndTime, forKey: .dagEndTime)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The operation state.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// Unused.
    case unknown
    /// The operation has been created.
    case pending
    /// The operation is running.
    case running
    /// The operation is done; either cancelled or completed.
    case done
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unknown
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unknown: return 0
      case .pending: return 1
      case .running: return 2
      case .done: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unknown: return "UNKNOWN"
      case .pending: return "PENDING"
      case .running: return "RUNNING"
      case .done: return "DONE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNKNOWN": self = .unknown
      case "PENDING": self = .pending
      case "RUNNING": self = .running
      case "DONE": self = .done
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unknown
      case 1: self = .pending
      case 2: self = .running
      case 3: self = .done
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unknown: return try container.encode("UNKNOWN")
      case .pending: return try container.encode("PENDING")
      case .running: return try container.encode("RUNNING")
      case .done: return try container.encode("DONE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.WorkflowMetadata"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
