// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A YARN application created by a job. Application information is a subset of
/// <code>org.apache.hadoop.yarn.proto.YarnProtos.ApplicationReportProto</code>.
///
/// **Beta Feature**: This report is available for testing purposes only. It may
/// be changed before final release.
public struct YarnApplication: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The application name.
  public var name: Swift.String = Swift.String()

  /// Required. The application state.
  public var state: YarnApplication.State = YarnApplication.State()

  /// Required. The numerical progress of the application, from 1 to 100.
  public var progress: Swift.Float = Swift.Float()

  /// Optional. The HTTP URL of the ApplicationMaster, HistoryServer, or
  /// TimelineServer that provides application-specific information. The URL uses
  /// the internal hostname, and requires a proxy server for resolution and,
  /// possibly, access.
  public var trackingUrl: Swift.String = Swift.String()

  /// Optional. The cumulative CPU time consumed by the application for a job,
  /// measured in vcore-seconds.
  public var vcoreSeconds: Swift.Int64 = Swift.Int64()

  /// Optional. The cumulative memory usage of the application for a job,
  /// measured in mb-seconds.
  public var memoryMbSeconds: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `YarnApplication`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = YarnApplication().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The application state, corresponding to
  /// <code>YarnProtos.YarnApplicationStateProto</code>.
  public enum State: Codable, Equatable, Sendable {
    /// Status is unspecified.
    case unspecified
    /// Status is NEW.
    case new
    /// Status is NEW_SAVING.
    case newSaving
    /// Status is SUBMITTED.
    case submitted
    /// Status is ACCEPTED.
    case accepted
    /// Status is RUNNING.
    case running
    /// Status is FINISHED.
    case finished
    /// Status is FAILED.
    case failed
    /// Status is KILLED.
    case killed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .new: return 1
      case .newSaving: return 2
      case .submitted: return 3
      case .accepted: return 4
      case .running: return 5
      case .finished: return 6
      case .failed: return 7
      case .killed: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .new: return "NEW"
      case .newSaving: return "NEW_SAVING"
      case .submitted: return "SUBMITTED"
      case .accepted: return "ACCEPTED"
      case .running: return "RUNNING"
      case .finished: return "FINISHED"
      case .failed: return "FAILED"
      case .killed: return "KILLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "NEW": self = .new
      case "NEW_SAVING": self = .newSaving
      case "SUBMITTED": self = .submitted
      case "ACCEPTED": self = .accepted
      case "RUNNING": self = .running
      case "FINISHED": self = .finished
      case "FAILED": self = .failed
      case "KILLED": self = .killed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .new
      case 2: self = .newSaving
      case 3: self = .submitted
      case 4: self = .accepted
      case 5: self = .running
      case 6: self = .finished
      case 7: self = .failed
      case 8: self = .killed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .new: return try container.encode(1)
      case .newSaving: return try container.encode(2)
      case .submitted: return try container.encode(3)
      case .accepted: return try container.encode(4)
      case .running: return try container.encode(5)
      case .finished: return try container.encode(6)
      case .failed: return try container.encode(7)
      case .killed: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataproc.v1.YarnApplication"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
